import { toast } from 'sonner'
import { useAppStore } from '../store'
import { getRuntimeEnvironmentIdForWorktree } from '@/lib/worktree-runtime-owner'
import { isRemoteRuntimePtyId } from '@/runtime/runtime-terminal-inspection'
import { isWebRuntimeSessionActive, createWebRuntimeSessionTerminal, createWebRuntimeSessionBrowserTab, activateWebRuntimeSessionTab, closeWebRuntimeSessionTab } from '@/runtime/web-runtime-session'
import { resumeSleepingAgentSessionsForWorktree } from '@/lib/resume-sleeping-agent-session'
import { launchAgentInNewTab } from '@/lib/launch-agent-in-new-tab'
import { translate } from '@/i18n/i18n'
import { listBoundAgentTabActions, resolveDefaultAgentForNewTab } from '@/lib/agent-tab-shortcuts'
import { focusTerminalTabSurface } from '@/lib/focus-terminal-tab-surface'
import { buildDuplicatedBrowserTabOptions } from '@/lib/duplicate-browser-tab-options'
import { browserWorkspaceHasRemoteOwner } from '@/runtime/remote-browser-tab-ownership'
import { closeTerminalTab } from './terminal/terminal-tab-actions'
import { canMountTerminalWorkspaceForStartup, applyBackgroundMountTabRestriction, planColdActivationTabDeferral, pruneClosedBackgroundMountTabs, revealActivationDeferredTabs, shouldMountBackgroundWorktreeTab, takeAllPendingBackgroundTerminalWorktreeMounts, takePendingBackgroundTerminalWorktreeMount } from './terminal/background-terminal-worktree-mount'
import { hasRegisteredRuntimeTerminalTab } from '../runtime/sync-runtime-graph'
import { terminalProviderHasAuthoritativeSnapshot } from './terminal/terminal-provider-snapshot-capability'
import { canDeferColdActivationTabsForHost, canWatcherCoverParkedTerminalTab, disposeAllParkedTerminalWatchers, pruneParkedTerminalWatchers, shouldDeferParkedPtyExitTabClose, syncParkedTerminalTabWatchers, terminalWatcherLiveWorkspaceIds } from './terminal-pane/terminal-parked-tab-watchers'
import { canParkTerminalWorktreeRenderers, getTerminalWorktreeColdParkRecheckDelayMs, selectColdParkedTerminalWorktrees } from './terminal-pane/terminal-hidden-view-parking'
import { selectForceParkEvictableTabIds, selectRetentionForceParkedTerminalWorktrees } from './terminal-pane/terminal-hidden-worktree-retention'
import { captureForceParkedWorktreeBuffers } from './terminal-pane/force-park-buffer-capture'
import { warnTerminalLifecycleAnomaly } from './terminal-pane/terminal-lifecycle-diagnostics'
import { getTerminalParkingPolicyOverrides, recordTerminalWorktreeParkingDebugVerdicts } from './terminal-pane/terminal-parking-e2e-overrides'
import { selectEvictionExemptTerminalTabIds } from './terminal-pane/terminal-eviction-exempt-tabs'
import { getEffectiveLayout } from './terminal/split-group-mount'
import { combineTerminalWorktreeParkIds, useManualTerminalWorktreeParking } from './terminal-pane/use-manual-terminal-worktree-parking'
import { useTerminalSurfaceSaveController } from './terminal-surface-save-controller'
import { useTerminalSurfaceParkingController } from './terminal-surface-parking-controller'
import { useTerminalSurfaceActions } from './terminal-surface-actions'

function getActiveWorktreeRuntimeEnvironmentId(worktreeId: string | null): string | null {
  return getRuntimeEnvironmentIdForWorktree(useAppStore.getState(), worktreeId)
}
export function useTerminalSurfaceControllerComposition(state: Record<string, any>): Record<string, any> {
  const {
    openFiles,
    activeWorktreeId,
    activeTabType,
    activeTabId,
    activeTabIdByWorktree,
    renderedActiveWorktreeId,
    tabs,
    tabsByWorktree,
    setActiveTab,
    setActiveTabType,
    setActiveWorktree,
    markFileDirty,
    closeFile,
    activeFileId,
    terminalParkingRevision,
    setTerminalParkingRevision,
    backgroundMountRevision,
    setBackgroundMountRevision,
    consumeSuppressedPtyExit,
    workspaceSessionReady,
    hydrationSucceeded,
    startupWorktreeRefreshCompleted,
    workspaceSurfaces,
    pendingStartupByTabId,
    terminalParkingEnabled,
    terminalSshParkingEnabled,
    runtimeStatusByEnvironmentId,
    pairedRuntimeParkingEnvironmentIds,
    terminalRetentionBudgetEnabled,
    terminalTitleSnapshotAuthorityEnabled,
    activeWorktreeDeferralHostId,
    layoutByWorktree,
    groupsByWorktree,
    activeGroupIdByWorktree,
    getEffectiveLayoutForWorktree,
    mountedWorktreeIdsRef,
    measurableBackgroundWorktreeIdsRef,
    terminalWorktreeHiddenSinceRef,
    measuringTerminalWorktreeIdsRef,
    terminalWorktreeParkCooldownUntilRef,
    terminalWorktreeParkingTimersRef,
    isRemoteRuntimePtyId,
    isParkRestorableTerminalPty,
    terminalProviderHasAuthoritativeSnapshot,
    selectPairedRuntimeParkingEnvironmentIds,
    selectColdParkedTerminalWorktrees,
    selectRetentionForceParkedTerminalWorktrees,
    selectForceParkEvictableTabIds,
    selectEvictionExemptTerminalTabIds,
    captureForceParkedWorktreeBuffers,
    warnTerminalLifecycleAnomaly,
    getTerminalParkingPolicyOverrides,
    recordTerminalWorktreeParkingDebugVerdicts,
    canParkTerminalWorktreeRenderers,
    getTerminalWorktreeColdParkRecheckDelayMs,
    combineTerminalWorktreeParkIds,
    useManualTerminalWorktreeParking,
    canDeferColdActivationTabsForHost,
    canWatcherCoverParkedTerminalTab,
    disposeAllParkedTerminalWatchers,
    pruneParkedTerminalWatchers,
    shouldDeferParkedPtyExitTabClose,
    syncParkedTerminalTabWatchers,
    terminalWatcherLiveWorkspaceIds,
    findActivityTerminalPortal,
    hasRegisteredRuntimeTerminalTab,
    canMountTerminalWorkspaceForStartup,
    applyBackgroundMountTabRestriction,
    planColdActivationTabDeferral,
    pruneClosedBackgroundMountTabs,
    revealActivationDeferredTabs,
    shouldMountBackgroundWorktreeTab,
    takeAllPendingBackgroundTerminalWorktreeMounts,
    takePendingBackgroundTerminalWorktreeMount,
    createTab,
    closeTab,
    setTabCustomTitle,
    setTabColor,
    setActiveFile,
    browserTabsByWorktree,
    createBrowserTab,
    openNewBrowserTabInActiveWorkspace,
    openNewMarkdownInActiveWorkspace,
    openNewTerminalTabInActiveWorkspace,
    closeBrowserTab,
    setActiveBrowserTab,
    setTabBarOrder,
    launchAgentInNewTab,
    getActiveWorktreeRuntimeEnvironmentId,
    isWebRuntimeSessionActive,
    createWebRuntimeSessionTerminal,
    createWebRuntimeSessionBrowserTab,
    activateWebRuntimeSessionTab,
    closeWebRuntimeSessionTab,
    buildDuplicatedBrowserTabOptions,
    destroyWorkspaceWebviews,
    handleCloseFile,
    queueEditorCloseRequests,
    closeTerminalTab,
    browserWorkspaceHasRemoteOwner,
    focusTerminalTabSurface,
    toast,
    translate,
    resolveDefaultAgentForNewTab,
    listBoundAgentTabActions,
    resumeSleepingAgentSessionsForWorktree,
  } = state


  const terminalSave = useTerminalSurfaceSaveController({
    openFiles,
    activeWorktreeId,
    activeTabType,
    activeTabId,
    activeTabIdByWorktree,
    renderedActiveWorktreeId,
    tabs,
    tabsByWorktree,
    setActiveTab,
    setActiveTabType,
    setActiveWorktree,
    markFileDirty,
    closeFile,
    activeFileId,
    terminalParkingRevision,
    setTerminalParkingRevision,
    backgroundMountRevision,
    setBackgroundMountRevision,
    consumeSuppressedPtyExit
  })
  const parking = useTerminalSurfaceParkingController({
    activeView,
    renderedActiveWorktreeId,
    workspaceSurfaces,
    tabsByWorktree,
    pendingStartupByTabId,
    terminalParkingEnabled,
    terminalSshParkingEnabled,
    runtimeStatusByEnvironmentId,
    pairedRuntimeParkingEnvironmentIds,
    terminalRetentionBudgetEnabled,
    terminalTitleSnapshotAuthorityEnabled,
    activeTabId,
    activeTabIdByWorktree,
    workspaceSessionReady,
    hydrationSucceeded,
    startupWorktreeRefreshCompleted,
    activityTerminalPortals,
    activeWorktreeDeferralHostId,
    layoutByWorktree,
    groupsByWorktree,
    activeGroupIdByWorktree,
    getEffectiveLayoutForWorktree,
    mountedWorktreeIdsRef,
    measurableBackgroundWorktreeIdsRef,
    terminalWorktreeHiddenSinceRef,
    measuringTerminalWorktreeIdsRef,
    terminalWorktreeParkCooldownUntilRef,
    terminalWorktreeParkingTimersRef,
    isRemoteRuntimePtyId,
    isParkRestorableTerminalPty,
    terminalProviderHasAuthoritativeSnapshot,
    selectPairedRuntimeParkingEnvironmentIds,
    selectColdParkedTerminalWorktrees,
    selectRetentionForceParkedTerminalWorktrees,
    selectForceParkEvictableTabIds,
    selectEvictionExemptTerminalTabIds,
    captureForceParkedWorktreeBuffers,
    warnTerminalLifecycleAnomaly,
    getTerminalParkingPolicyOverrides,
    recordTerminalWorktreeParkingDebugVerdicts,
    canParkTerminalWorktreeRenderers,
    getTerminalWorktreeColdParkRecheckDelayMs,
    combineTerminalWorktreeParkIds,
    useManualTerminalWorktreeParking,
    canDeferColdActivationTabsForHost,
    canWatcherCoverParkedTerminalTab,
    disposeAllParkedTerminalWatchers,
    pruneParkedTerminalWatchers,
    shouldDeferParkedPtyExitTabClose,
    syncParkedTerminalTabWatchers,
    terminalWatcherLiveWorkspaceIds,
    findActivityTerminalPortal,
    hasRegisteredRuntimeTerminalTab,
    canMountTerminalWorkspaceForStartup,
    applyBackgroundMountTabRestriction,
    planColdActivationTabDeferral,
    pruneClosedBackgroundMountTabs,
    revealActivationDeferredTabs,
    shouldMountBackgroundWorktreeTab,
    takeAllPendingBackgroundTerminalWorktreeMounts,
    takePendingBackgroundTerminalWorktreeMount
  })
  const terminalActions = useTerminalSurfaceActions({
    activeWorktreeId,
    createTab,
    setActiveTabType,
    openNewTerminalTabInActiveWorkspace,
    setTabBarOrder,
    activeTabId,
    closeTab,
    closeBrowserTab,
    closeFile,
    setActiveTab,
    setActiveWorktree,
    setActiveBrowserTab,
    setActiveFile,
    setTabCustomTitle,
    setTabColor,
    launchAgentInNewTab,
    browserTabsByWorktree,
    openFiles,
    getActiveWorktreeRuntimeEnvironmentId,
    isWebRuntimeSessionActive,
    createWebRuntimeSessionTerminal,
    createWebRuntimeSessionBrowserTab,
    activateWebRuntimeSessionTab,
    closeWebRuntimeSessionTab,
    openNewBrowserTabInActiveWorkspace,
    consumeSuppressedPtyExit,
    openNewMarkdownInActiveWorkspace,
    createBrowserTab,
    buildDuplicatedBrowserTabOptions,
    destroyWorkspaceWebviews,
    closeTerminalTab,
    browserWorkspaceHasRemoteOwner,
    focusTerminalTabSurface,
    toast,
    translate,
    resolveDefaultAgentForNewTab,
    listBoundAgentTabActions,
    resumeSleepingAgentSessionsForWorktree
  })
  return {
    ...terminalSave,
    ...parking,
    ...terminalActions,
    terminalSave,
    parking,
    terminalActions
  }
}
