export function useTerminalSurfaceInputEffects(context: Record<string, any>): void {
  const {
    useTerminalSurfaceKeyboard,
    useTerminalSurfaceEffects
  } = context
  useTerminalSurfaceKeyboard({
    activeWorktreeId,
    keybindings,
    terminalShortcutPolicy,
    handleNewBrowserTab,
    handleNewFile,
    handleNewTab,
    handleNewAgentTab,
    handleCloseTab,
    handleCloseBrowserTab,
    handlePtyExit,
    closeBrowserTab,
    handleCloseFile,
    handleCloseAllFiles,
    createFloatingWorkspaceTerminalTab,
    createFloatingWorkspaceBrowserTab,
    isFloatingWorkspacePanelFocused,
    switchFloatingWorkspaceTab,
    keybindingMatchesAction,
    showTerminalShortcutCaptureNotification,
    getKeybindingContext,
    handleSwitchRecentTab,
    handleSwitchTab,
    handleSwitchTabAcrossAllTypes,
    handleSwitchTerminalTab,
    createFloatingWorkspaceMarkdownTab,
    handleEmptyFloatingWorkspacePanelCloseShortcut,
    isEventTargetInsideFloatingWorkspacePanel,
    matchesRecentTabSwitcherChord,
    toast,
    translate
  })
  useTerminalSurfaceEffects({
    openFiles,
    activeWorktreeId,
    activeWorktreeBrowserTabIdsKey,
    activeTabType,
    activeBrowserTabId,
    renderedActiveWorktreeId,
    setActiveBrowserTab,
    setActiveTabType,
    browserTabsByWorktree,
    activeView,
    workspaceSurfaces,
    destroyRemovedBrowserWebview,
    collectBrowserWebviewIds,
    destroyWorkspaceWebviews,
    setWindowCloseRequestHandler,
    isIntentionalAppRestartInProgress,
    preventUnloadAndScheduleShutdownCheckpointReset,
    proceedToNativeWindowClose,
    queueEditorCloseRequests,
    windowCloseAfterDirtyRef
  })

}

