import { useMobileSessionDocumentActions } from './use-mobile-session-document-actions'
import { useMobileSessionRecovery } from './use-mobile-session-recovery'
import { useMobileSessionTabInteractions } from './use-mobile-session-tab-interactions'
import { useMobileSessionTerminalInput } from './use-mobile-session-terminal-input'
import { useMobileSessionCreation } from './use-mobile-session-creation'
import { useMobileSessionActions } from './use-mobile-session-actions'
import { createBulkCloseSheetActions, createCloseWithBulkActions } from '../../../../src/session/mobile-bulk-close-sheet-actions'
import { runAcceptedMobileSessionTabsEffects } from '../../../../src/session/mobile-session-tabs-accepted-effects'
import { buildMobileQuickCommandLaunch, supportsMobileQuickCommands } from '../../../../src/terminal/quick-commands'
import { captureMobileFileMutationOwnership } from '../../../../src/files/mobile-file-mutation-ownership'
import { normalizeBrowserUrl } from '../../../../src/browser/browser-url'
import { isFileExistsErrorMessage } from '../../../../src/session/mobile-session-route-helpers'
import { loadMobileNewTabAgentOptions } from '../../../../src/session/mobile-new-tab-agent-loader'
import { useCallback } from 'react'
import { triggerError } from '../../../../src/platform/haptics'

type WorkspaceContext = Record<string, any>

export function useMobileSessionWorkspaceBehavior(context: WorkspaceContext) {
  const { client, setMarkdownDocs, worktreeId, setFileDocs, connState, isFloatingWorkspaceRoute,
    setDiffComments, diffCommentsRef, diffCommentBusy, persistDiffComments, showToast,
    setPendingDiffNotesDelivery, markdownDocs, setLeaveDrafts, setDiscardMarkdownTarget,
    discardMarkdownTarget, markdownSaveInFlightRef, markdownSaveSeqRef, sessionTabs, router, hostId,
    runAcceptedMobileSessionTabsEffects: acceptedEffects = runAcceptedMobileSessionTabsEffects,
    pendingBrowserFocusPageIdRef, switchSessionTabRef, closedTabTombstonesRef, nativeChatStream,
    appliedSessionTabsRevisionRef, appliedSnapshotMarkerRef, applySessionTabs, fetchTerminals, terminalGestureInputQueuesRef,
    terminalGestureInputInFlightRef, setBrowserScreencastSupported, setAgentSessionHistorySupported,
    setQuickCommandsSupported, setShowQuickCommands, startRuntimeCapabilityProbe,
    setHostEndpoint, deviceTokenRef, loadHosts, loadCustomKeys, setCustomKeys, loadTerminalAccessoryLayout,
    setVisibleBuiltInIds, terminalRefs, activeHandleRef, initializedHandlesRef, connStateRef,
    unsubscribeTerminal, subscribeToTerminal, scheduleDelayedAction, terminalFrameHeightRef, viewportRef,
    viewportMeasuredRef, showNativeChatRef, clientRef, terminals, terminalTextScale, terminalFrameWidth,
    setKeyboardHeight, tabLayoutsRef, tabStripViewportWidthRef, tabStripContentWidthRef, tabStripOffsetRef,
    tabStripRef, activeSessionTabId, customKeys, saveCustomKeys, sessionTabActionSheetRequestSeqRef,
    sessionTabActionSheetKeyboardHideSubRef, clearTerminalCache, pendingActiveSessionTabIdRef,
    pendingActiveTerminalHandleRef, pendingTerminalActivationAttemptRef, initialSessionAutoCreateRef,
    createInitialSessionAutoCreateState, setActiveHandle, setTerminals, terminalsRef, setSessionTabs,
    setActiveSessionTabId, clearPendingLiveInputCommit, clearDelayedActionTimers, setTerminalsLoaded,
    created, headlessActivationNeedsHostRenderer, loadTerminalTextScale, setTerminalTextScale,
    loadTerminalAutocompleteEnabled, setAutocompleteEnabled, loadTerminalLinkOpenMode, setTerminalLinkOpenMode,
    creatingTerminalRef, creatingBrowser, creatingMarkdown, setCreatingMarkdown, setCreateError,
    handleCreateTerminal, setCreatingBrowser, browserScreencastSupportedRef, fetchSessionTabs,
    fetchPendingBrowserSessionTabs, handleCreateBrowserRef, renameTarget, setRenameTarget, clearTerminalLiveInputDefault,
    activeSessionTabIdRef, activeSessionTabTypeRef, defaultTerminalHandlesToLiveInput, pendingActiveSessionTabId,
    createError, createWarning, setShowCreateTabDrawer, setCreating, setCreateWarningState, setShowCreateBrowserModal,
    setShowHeaderMoreActions, actionTarget, setActionTarget, markdownActionTarget, setMarkdownActionTarget,
    fileActionTarget, setFileActionTarget, browserActionTarget, setBrowserActionTarget, leaveDrafts,
    setLeaveDrafts, setDeleteKeyTarget, setShowCustomKeyModal, setDictationMode, dictation, input,
    setInput, activeHandle, activeSessionTab, canSend, canCompose, liveInputEnabled, liveInputTerminalHandles,
    liveInputTerminalHandlesRef, sendLiveTerminalInputRef, terminalModes, toggleDisplayMode, commandInputRef,
    liveInputRef, setLiveInputCapture, liveInputCapture, ptyModesRef, terminalGestureInputBucketsRef,
    terminalCwdRef, sendingRef, terminalFrameHeightRef: frameHeightRef, setTerminalFrameWidth,
    terminalKeyboardMetrics, setTerminalKeyboardMetrics, selectModeActive, setSelectModeActive, canPaste,
    setCanPaste, handleAccessoryKey, handlePaste, handleSend, handleLiveInputChange, handleLiveInputKeyPress,
    handleLiveInputSubmit, handleDictationToggle, handleDictationPressIn, handleDictationPressOut,
    startDictation, cancelDictation, terminalRefs: refs, terminalTextScale: textScale,
    hostQueryReplyInputSupportedRef, keyboardHeight, nativeChatController, showNativeChat,
    nativeChatInputLockReason, nativeChatSendError, nativeChatImages, dictationMode, isAttaching,
    attachImage, handleTerminalInput, handleTerminalQueryReply, handleTerminalTap, handleTerminalOpenUrl,
    handleFileTap, handleSelectionMode, handleSelectionCopy, handleSelectionEvicted, handleModesChanged,
    handleKeyboardAvoidanceMetrics, handleHaptic, setTerminalWebViewRef, handleTerminalWebReady,
    launchQuickCommand, quickCommandsSupported, createTabAgentActions, sendDiffNotesAgentActions,
    handleCloseSessionTab, handleCloseTerminal, handleClearTerminal, handleRenameTerminal,
    handleBrowserNavigationCommand, handleFileOpenStart, handleOpenedFileDiff, setMobileSessionRootRef,
    activePanel, setActivePanel, sessionContentRowWidth, setSessionContentRowWidth, canDockPanel,
    showConnectionRetry, terminalSummary, visibleTabs, showLoadingState, showEmptyState, activeMarkdownTab,
    activeFileTab, activeBrowserTab, activePendingTerminalTab, createTabBusy, keyboardLift,
    activeTerminalKeyboardLift, toastMessage, toastAnimatedStyle, worktreeName, insets,
    showHeaderMoreButton, showAgentSessionHistoryAction, showChecksAction } = context
  const {
    readMarkdownTab,
    readFileTab,
    loadDiffComments,
    persistDiffComments,
    addDiffCommentForFile,
    deleteDiffCommentForFile,
    copyDiffCommentsToClipboard,
    sendDiffCommentsToAgent,
    clearDeliveredDiffComments,
    updateMarkdownLocalContent,
    copyMarkdownLocalContent,
    getDirtyMarkdownDrafts,
    leaveSession,
    requestLeaveSession,
    discardMarkdownLocalContent,
    confirmDiscardMarkdown,
    saveMarkdownTab
  } = useMobileSessionDocumentActions({
    client,
    setMarkdownDocs,
    worktreeId,
    setFileDocs,
    connState,
    isFloatingWorkspaceRoute,
    setDiffComments,
    diffCommentsRef,
    diffCommentBusy,
    setDiffCommentBusy,
    persistDiffComments,
    showToast,
    setPendingDiffNotesDelivery,
    markdownDocs,
    setLeaveDrafts,
    setDiscardMarkdownTarget,
    discardMarkdownTarget,
    markdownSaveInFlightRef,
    markdownSaveSeqRef,
    sessionTabs,
    router,
    hostId
  })

  const {
    consumeAcceptedSessionTabs,
    hasSessionTabsRecoveryNeed,
    getSessionTabsApplicationRevision,
    fetchSessionTabs,
    ensureSessionTabs,
    fetchPendingBrowserSessionTabs,
    hostQueryReplyInputSupportedRef,
    pendingForegroundRecoveryRef,
    notifyTerminalFrameHeight,
    notifyKeyboardVisibility,
    scrollActiveTabIntoView,
    handleDeleteCustomKey,
    handleManageShortcuts
  } = useMobileSessionRecovery({
    runAcceptedMobileSessionTabsEffects,
    pendingBrowserFocusPageIdRef,
    switchSessionTabRef,
    setMarkdownDocs,
    closedTabTombstonesRef,
    nativeChatStream,
    appliedSessionTabsRevisionRef,
    appliedSnapshotMarkerRef,
    worktreeId,
    terminalDiagnosticsRef,
    client,
    connState,
    applySessionTabs,
    fetchTerminals,
    terminalGestureInputQueuesRef,
    terminalGestureInputInFlightRef,
    setBrowserScreencastSupported,
    setAgentSessionHistorySupported,
    setQuickCommandsSupported,
    setShowQuickCommands,
    setShowCustomKeyModal,
    startRuntimeCapabilityProbe,
    MOBILE_AI_VAULT_CAPABILITY,
    supportsMobileQuickCommands,
    TERMINAL_QUERY_REPLY_INPUT_RUNTIME_CAPABILITY,
    hostId,
    deviceTokenRef,
    setHostEndpoint,
    loadHosts,
    loadCustomKeys,
    setCustomKeys,
    loadTerminalAccessoryLayout,
    setVisibleBuiltInIds,
    terminalRefs,
    shouldRecoverTerminalOnAppStateChange,
    Platform,
    recoverActiveTerminalAfterForeground,
    activeHandleRef,
    initializedHandlesRef,
    connStateRef,
    unsubscribeTerminal,
    subscribeToTerminal,
    scheduleDelayedAction,
    terminalFrameHeightRef,
    viewportRef,
    viewportMeasuredRef,
    showNativeChatRef,
    clientRef,
    terminals,
    terminalTextScale,
    terminalFrameWidth,
    setKeyboardHeight,
    Keyboard,
    tabLayoutsRef,
    tabStripViewportWidthRef,
    tabStripContentWidthRef,
    tabStripOffsetRef,
    tabStripRef,
    resolveTabStripScrollOffset,
    activeSessionTabId,
    AsyncStorage,
    customKeys,
    saveCustomKeys,
    router,
    sessionTabActionSheetRequestSeqRef,
    sessionTabActionSheetKeyboardHideSubRef,
    clearTerminalCache,
    pendingActiveSessionTabIdRef,
    pendingActiveTerminalHandleRef,
    pendingTerminalActivationAttemptRef,
    initialSessionAutoCreateRef,
    createInitialSessionAutoCreateState,
    setActiveHandle,
    setTerminals,
    terminalsRef,
    setSessionTabs,
    setActiveSessionTabId,
    clearPendingLiveInputCommit,
    clearDelayedActionTimers,
    setTerminalsLoaded,
    created,
    isFloatingWorkspaceRoute,
    headlessActivationNeedsHostRenderer,
    showToast,
    loadTerminalTextScale,
    setTerminalTextScale,
    loadTerminalAutocompleteEnabled,
    setAutocompleteEnabled,
    loadTerminalLinkOpenMode,
    setTerminalLinkOpenMode
  })

  // Why: unsubscribe restores old dims (clears phone-fit banner); resubscribe phone-fits the new one.
  const {
    switchTab,
    switchSessionTab,
    setTerminalWebViewRef,
    handleTerminalWebReady,
    handleSend,
    handleAccessoryKey,
    sendLiveTerminalInput,
    focusLiveInput,
    clearSessionTabActionSheetKeyboardListener,
    openSessionTabActionSheet,
    openSessionTabActionSheetAfterKeyboardDismiss,
    dismissSoftwareKeyboard,
    handleTerminalTap,
    handleFileTapActivationSeqRef,
    handleFileTap,
    handleOpenedFileDiffActivationSeqRef,
    fileOpenStartActiveTabIdRef,
    handleFileOpenStart,
    handleOpenedFileDiff,
    handleTerminalOpenUrl,
    sendLiveTerminalInputRef
  } = useMobileSessionTabInteractions({
    triggerSelection,
    sessionTabs,
    terminalDiagnosticsRef,
    pendingActiveSessionTabIdRef,
    pendingActiveTerminalHandleRef,
    activeSessionTabTypeRef,
    defaultTerminalHandlesToLiveInput,
    setActiveSessionTabId,
    activeHandleRef,
    setActiveHandle,
    unsubscribeTerminal,
    initializedHandlesRef,
    terminalUnsubsRef,
    subscribeToTerminal,
    client,
    activateMobileSessionTab,
    worktreeId,
    readFileTab,
    markdownDocs,
    readMarkdownTab,
    switchSessionTabRef,
    terminalRefs,
    terminalGestureInputBucketsRef,
    terminalGestureInputQueuesRef,
    terminalGestureInputInFlightRef,
    webReadyHandlesRef,
    nativeChatStream,
    measureViewportOnce,
    activeSessionTab,
    fileDocs,
    sendingRef,
    canSend,
    input,
    setInput,
    deviceTokenRef,
    buildTerminalSendParams,
    TERMINAL_INPUT_SEND_OPTIONS,
    handleLiveInputAccessoryBytes,
    clientRef,
    connStateRef,
    sendTerminalLiveAccessoryRawBytes,
    normalizeTerminalTextInput,
    isTerminalLiveInputWithinByteLimit,
    triggerError,
    showToast,
    isTerminalSendRpcAccepted,
    liveInputEnabled,
    focusTerminalLiveInputTarget,
    keyboardHeight,
    scheduleTerminalLiveInputFocus,
    liveInputRef,
    liveInputFocusTimerRef,
    sessionTabActionSheetKeyboardHideSubRef,
    setActionTarget,
    setMarkdownActionTarget,
    setFileActionTarget,
    setBrowserActionTarget,
    clearTerminalLiveInputFocusTimer,
    scheduleDelayedAction,
    commandInputRef,
    dismissTerminalKeyboard,
    handleCreateBrowserRef,
    hostId,
    routeWorktreeName,
    router,
    terminalCwdRef,
    fetchSessionTabs,
    sessionTabsRef,
    activeSessionTabIdRef,
    activateOpenedSourceControlDiffTab,
    terminalLinkOpenMode,
    isFloatingWorkspaceRoute
  })

  const {
    toggleLiveInput,
    allowTerminalGestureInput,
    flushTerminalGestureInput,
    enqueueTerminalGestureInput,
    handleTerminalInput,
    handleTerminalQueryReply,
    handleClearTerminal,
    handleAccessoryKeyRef,
    stopAccessoryRepeat,
    startAccessoryRepeat,
    setMobileSessionRootRef,
    handleSelectionMode,
    handleSelectionCopy,
    handleSelectionEvicted,
    handleModesChanged,
    handleKeyboardAvoidanceMetrics,
    handleHaptic
  } = useMobileSessionTerminalInput({
    activeHandle,
    toggleTerminalLiveInput,
    clearPendingLiveInputCommit,
    scheduleTerminalLiveInputFocus,
    liveInputFocusTimerRef,
    clearTerminalLiveInputFocusTimer,
    liveInputRef,
    terminalGestureInputBucketsRef,
    TERMINAL_GESTURE_INPUT_BUCKET_CAPACITY,
    TERMINAL_GESTURE_INPUT_REFILL_PER_SECOND,
    terminalGestureInputQueuesRef,
    terminalGestureInputInFlightRef,
    activeHandleRef,
    activeSessionTabTypeRef,
    clientRef,
    connStateRef,
    buildTerminalSendParams,
    deviceTokenRef,
    TERMINAL_INPUT_SEND_OPTIONS,
    TERMINAL_GESTURE_INPUT_MAX_QUEUE_AGE_MS,
    TERMINAL_GESTURE_INPUT_MAX_PENDING_SEQUENCES,
    TERMINAL_GESTURE_INPUT_FLUSH_DELAY_MS,
    client,
    connState,
    ptyModesRef,
    isGestureMouseTrackingMode,
    countTerminalGestureInputSequences,
    sendMobileTerminalQueryReply,
    hostQueryReplyInputSupportedRef,
    terminalUnsubsRef,
    getTerminalRef,
    showToast,
    handleAccessoryKey,
    toastSeqRef,
    clearTerminalCache,
    clearToastHideTimer,
    clearDelayedActionTimers,
    sessionTabActionSheetRequestSeqRef,
    clearSessionTabActionSheetKeyboardListener,
    setSelectModeActive,
    terminalRefs,
    setTerminalKeyboardMetrics,
    initialModesSeenRef,
    triggerSelection,
    triggerSuccess,
    triggerError,
    triggerEdgeBump,
    setMobileSessionRootRef
  })

  const {
    getActiveWorktreeConnectionId,
    refreshCanPaste,
    handlePaste,
    flushPendingLiveInputBeforeAttachmentSend,
    attachImage,
    isAttaching,
    nativeChatImages,
    handleCreateTerminal
  } = useMobileSessionCreation({
    client,
    isFloatingWorkspaceRoute,
    worktreeId,
    getRepoIdFromMobileWorktreeId,
    setCanPaste,
    activeHandle,
    activeHandleRef,
    activeSessionTabTypeRef,
    canSend,
    connState,
    connStateRef,
    clientRef,
    deviceTokenRef,
    flushPendingLiveInputBeforeExternalSend,
    nativeChatInputLeaseReadyRef,
    nativeChatInputLeaseReady,
    nativeChatScopeKey,
    nativeChatController,
    nativeChatSendError,
    ptyModesRef,
    refreshCanPaste,
    showToast,
    triggerError,
    triggerSelection,
    selectModeActive,
    terminalRefs,
    showCreateTabDrawer,
    pendingDiffNotesDelivery,
    setCreateTabAgentLoadState,
    setCreateTabAgentOptions,
    loadMobileNewTabAgentOptions,
    creatingTerminalRef,
    setCreating,
    setCreateError,
    activeSessionTab,
    unsubscribeTerminal,
    initializedHandlesRef,
    pendingActiveSessionTabIdRef,
    setActiveSessionTabId,
    setSessionTabs,
    defaultTerminalHandlesToLiveInput,
    pendingActiveTerminalHandleRef,
    setActiveHandle,
    setTerminals,
    terminalsRef,
    terminalRecordsEqual,
    subscribeToTerminal,
    options,
    scheduleDelayedAction,
    fetchSessionTabs,
    creatingMarkdown,
    creatingBrowser,
    browserScreencastSupportedRef,
    normalizeBrowserUrl,
    setCreatingMarkdown,
    setCreatingBrowser,
    fetchPendingBrowserSessionTabs,
    pendingBrowserFocusPageIdRef,
    setTerminalsLoaded,
    fetchTerminals,
    renameTarget,
    setRenameTarget,
    clearTerminalLiveInputDefault,
    terminals,
    sessionTabsRef,
    closedTabTombstonesRef,
    activeSessionTabIdRef
  })

  const {
    launchQuickCommand,
    handleCreateMarkdownNote,
    handleCreateBrowser,
    handleBrowserNavigationCommand,
    handleRenameTerminal,
    handleCloseTerminal,
    handleCloseSessionTab
  } = useMobileSessionActions({
    client,
    connState,
    creatingTerminalRef,
    creatingBrowser,
    creatingMarkdown,
    buildMobileQuickCommandLaunch,
    triggerError,
    showToast,
    handleCreateTerminal,
    setCreatingMarkdown,
    setCreateError,
    worktreeId,
    captureMobileFileMutationOwnership,
    isFileExistsErrorMessage,
    scheduleDelayedAction,
    fetchSessionTabs,
    setCreatingBrowser,
    browserScreencastSupportedRef,
    normalizeBrowserUrl,
    pendingBrowserFocusPageIdRef,
    fetchPendingBrowserSessionTabs,
    handleCreateBrowserRef,
    renameTarget,
    setRenameTarget,
    setTerminals,
    terminalsRef,
    fetchTerminals,
    unsubscribeTerminal,
    terminalRefs,
    initializedHandlesRef,
    clearTerminalLiveInputDefault,
    terminals,
    activeHandleRef,
    pendingActiveTerminalHandleRef,
    setActiveHandle,
    subscribeToTerminal,
    sessionTabsRef,
    setSessionTabs,
    closedTabTombstonesRef,
    activeSessionTabIdRef,
    activeSessionTabTypeRef,
    setActiveSessionTabId,
    defaultTerminalHandlesToLiveInput,
    pendingActiveSessionTabIdRef
  })

  return { ...context, ...{
    readMarkdownTab, readFileTab, loadDiffComments, persistDiffComments, addDiffCommentForFile,
    deleteDiffCommentForFile, copyDiffCommentsToClipboard, sendDiffCommentsToAgent, clearDeliveredDiffComments,
    updateMarkdownLocalContent, copyMarkdownLocalContent, getDirtyMarkdownDrafts, leaveSession,
    requestLeaveSession, discardMarkdownLocalContent, confirmDiscardMarkdown, saveMarkdownTab,
    consumeAcceptedSessionTabs, hasSessionTabsRecoveryNeed, getSessionTabsApplicationRevision,
    fetchSessionTabs, ensureSessionTabs, fetchPendingBrowserSessionTabs, hostQueryReplyInputSupportedRef,
    pendingForegroundRecoveryRef, notifyTerminalFrameHeight, notifyKeyboardVisibility,
    scrollActiveTabIntoView, handleDeleteCustomKey, handleManageShortcuts, bulkCloseActions,
    closeWithBulkActions, handleCloseSessionTab, handleCloseTerminal, handleClearTerminal,
    handleRenameTerminal, handleBrowserNavigationCommand, handleFileOpenStart, handleOpenedFileDiff,
    handleCreateBrowser, handleCreateMarkdownNote, handleCreateTerminal, launchQuickCommand,
    setTerminalWebViewRef, handleTerminalWebReady, handleSelectionMode, handleSelectionCopy,
    handleSelectionEvicted, handleModesChanged, handleKeyboardAvoidanceMetrics, handleHaptic,
    handleTerminalInput, handleTerminalQueryReply, handleTerminalTap, handleFileTap, handleTerminalOpenUrl,
    handleDictationToggle, handleDictationPressIn, handleDictationPressOut, startDictation, cancelDictation,
    handleLiveInputChange, handleLiveInputKeyPress, handleLiveInputSubmit, handleSend, handlePaste,
    handleAccessoryKey, toggleDisplayMode, createTabAgentActions, sendDiffNotesAgentActions,
    createTabBusy, activeMarkdownTab, activeFileTab, activeBrowserTab, activePendingTerminalTab,
    showLoadingState, showEmptyState, terminalSummary, showConnectionRetry, keyboardLift,
    activeTerminalKeyboardLift, toastAnimatedStyle, showHeaderMoreButton, showAgentSessionHistoryAction,
    showChecksAction, visibleTabs
  } }
}
