import { useMobileSessionDocumentActions } from './use-mobile-session-document-actions'
import { useMobileSessionRecovery } from './use-mobile-session-recovery'
import { useMobileSessionTerminalInput } from './use-mobile-session-terminal-input'
import { useMobileSessionCreation } from './use-mobile-session-creation'
import { useMobileSessionActions } from './use-mobile-session-actions'
import {
  createBulkCloseSheetActions,
  createCloseWithBulkActions
} from '../../../../src/session/mobile-bulk-close-sheet-actions'
import { runAcceptedMobileSessionTabsEffects } from '../../../../src/session/mobile-session-tabs-accepted-effects'
import {
  buildMobileQuickCommandLaunch,
  supportsMobileQuickCommands
} from '../../../../src/terminal/quick-commands'
import { captureMobileFileMutationOwnership } from '../../../../src/files/mobile-file-mutation-ownership'
import { normalizeBrowserUrl } from '../../../../src/browser/browser-url'
import {
  getRepoIdFromMobileWorktreeId,
  isFileExistsErrorMessage,
  isGestureMouseTrackingMode,
  TERMINAL_GESTURE_INPUT_BUCKET_CAPACITY,
  TERMINAL_GESTURE_INPUT_FLUSH_DELAY_MS,
  TERMINAL_GESTURE_INPUT_MAX_PENDING_SEQUENCES,
  TERMINAL_GESTURE_INPUT_MAX_QUEUE_AGE_MS,
  TERMINAL_GESTURE_INPUT_REFILL_PER_SECOND
} from '../../../../src/session/mobile-session-route-helpers'
import { loadMobileNewTabAgentOptions } from '../../../../src/session/mobile-new-tab-agent-loader'
import { resolveTabStripScrollOffset } from '../../../../src/session/tab-strip-scroll'
import { MOBILE_AI_VAULT_CAPABILITY } from '../../../../src/agent-history/agent-history-capability'
import { TERMINAL_QUERY_REPLY_INPUT_RUNTIME_CAPABILITY } from '../../../../../src/shared/protocol-version'
import { sendMobileTerminalQueryReply } from '../../../../src/terminal/mobile-terminal-query-reply'
import { countTerminalGestureInputSequences } from '../../../../src/terminal/terminal-gesture-input'
import {
  buildTerminalSendParams,
  TERMINAL_INPUT_SEND_OPTIONS
} from '../../../../src/terminal/terminal-send-request'
import {
  clearTerminalLiveInputFocusTimer,
  scheduleTerminalLiveInputFocus
} from '../../../../src/terminal/terminal-live-input'
import type { MobileNewTabAgentOption } from '../../../../src/session/mobile-new-tab-agent-options'
import { terminalRecordsEqual } from '../../../../src/session/mobile-terminal-records'
import { Bot } from 'lucide-react-native'
import { MobileAgentIcon } from '../../../../src/components/MobileAgentIcon'
import { createElement } from 'react'
import {
  triggerEdgeBump,
  triggerError,
  triggerSelection,
  triggerSuccess
} from '../../../../src/platform/haptics'
import AsyncStorage from '@react-native-async-storage/async-storage'
import { Keyboard } from 'react-native'
import { useMobileSessionWorkspaceTerminalInteractions } from './mobile-session-workspace-terminal-interactions'

type WorkspaceContext = Record<string, any>

export function useMobileSessionWorkspaceBehavior(context: WorkspaceContext) {
  const {
    client,
    setMarkdownDocs,
    worktreeId,
    routeWorktreeName,
    setFileDocs,
    connState,
    isFloatingWorkspaceRoute,
    setDiffComments,
    diffCommentsRef,
    diffCommentBusy,
    setDiffCommentBusy,
    showToast,
    setPendingDiffNotesDelivery,
    markdownDocs,
    setLeaveDrafts,
    setDiscardMarkdownTarget,
    discardMarkdownTarget,
    markdownSaveInFlightRef,
    markdownSaveSeqRef,
    sessionTabs,
    sessionTabsRef,
    router,
    hostId,
    pendingBrowserFocusPageIdRef,
    switchSessionTabRef,
    closedTabTombstonesRef,
    appliedSessionTabsRevisionRef,
    appliedSnapshotMarkerRef,
    applySessionTabs,
    terminalDiagnosticsRef,
    getTerminalRef,
    fetchTerminals,
    terminalGestureInputQueuesRef,
    terminalGestureInputInFlightRef,
    setBrowserScreencastSupported,
    setAgentSessionHistorySupported,
    setQuickCommandsSupported,
    setShowQuickCommands,
    startRuntimeCapabilityProbe,
    setHostEndpoint,
    deviceTokenRef,
    loadHosts,
    loadCustomKeys,
    setCustomKeys,
    loadTerminalAccessoryLayout,
    setVisibleBuiltInIds,
    terminalRefs,
    activeHandleRef,
    initializedHandlesRef,
    connStateRef,
    unsubscribeTerminal,
    subscribeToTerminal,
    scheduleDelayedAction,
    terminalFrameHeightRef,
    viewportRef,
    viewportMeasuredRef,
    clientRef,
    terminals,
    terminalTextScale,
    terminalFrameWidth,
    setKeyboardHeight,
    tabLayoutsRef,
    tabStripViewportWidthRef,
    tabStripContentWidthRef,
    tabStripOffsetRef,
    tabStripRef,
    activeSessionTabId,
    customKeys,
    saveCustomKeys,
    sessionTabActionSheetRequestSeqRef,
    sessionTabActionSheetKeyboardHideSubRef,
    clearTerminalCache,
    pendingActiveSessionTabIdRef,
    pendingActiveTerminalHandleRef,
    pendingTerminalActivationAttemptRef,
    initialSessionAutoCreateRef,
    createInitialSessionAutoCreateState,
    setActiveHandle,
    setTerminals,
    terminalsRef,
    setSessionTabs,
    setActiveSessionTabId,
    clearPendingLiveInputCommit,
    clearDelayedActionTimers,
    setTerminalsLoaded,
    created,
    creating,
    headlessActivationNeedsHostRenderer,
    loadTerminalTextScale,
    setTerminalTextScale,
    loadTerminalAutocompleteEnabled,
    setAutocompleteEnabled,
    loadTerminalLinkOpenMode,
    setTerminalLinkOpenMode,
    creatingTerminalRef,
    creatingBrowser,
    creatingMarkdown,
    setCreatingMarkdown,
    setCreateError,
    setCreateTabAgentLoadState,
    setCreateTabAgentOptions,
    createTabAgentLoadState,
    createTabAgentOptions,
    setCreatingBrowser,
    browserScreencastSupportedRef,
    handleCreateBrowserRef,
    renameTarget,
    setRenameTarget,
    clearTerminalLiveInputDefault,
    activeSessionTabIdRef,
    activeSessionTabTypeRef,
    defaultTerminalHandlesToLiveInput,
    createError,
    setShowCreateTabDrawer,
    setCreating,
    setCreateWarningState,
    setShowCreateBrowserModal,
    setShowHeaderMoreActions,
    actionTarget,
    setActionTarget,
    markdownActionTarget,
    setMarkdownActionTarget,
    fileActionTarget,
    setFileActionTarget,
    browserActionTarget,
    setBrowserActionTarget,
    leaveDrafts,
    setDeleteKeyTarget,
    setShowCustomKeyModal,
    setDictationMode,
    dictation,
    input,
    setInput,
    activeHandle,
    activeSessionTab,
    canSend,
    canCompose,
    liveInputEnabled,
    liveInputTerminalHandles,
    toggleTerminalLiveInput,
    liveInputTerminalHandlesRef,
    sendLiveTerminalInputRef,
    commandInputRef,
    liveInputRef,
    setLiveInputCapture,
    liveInputCapture,
    ptyModesRef,
    terminalGestureInputBucketsRef,
    terminalCwdRef,
    sendingRef,
    setTerminalFrameWidth,
    terminalKeyboardMetrics,
    setTerminalKeyboardMetrics,
    selectModeActive,
    setSelectModeActive,
    canPaste,
    setCanPaste,
    handleLiveInputChange,
    handleLiveInputKeyPress,
    handleLiveInputSubmit,
    handleDictationToggle,
    handleDictationPressIn,
    handleDictationPressOut,
    startDictation,
    cancelDictation,
    keyboardHeight,
    dictationMode,
    initialModesSeenRef,
    liveInputFocusTimerRef,
    terminalUnsubsRef,
    webReadyHandlesRef,
    toastSeqRef,
    clearToastHideTimer,
    flushPendingLiveInputBeforeExternalSend,
    fileDocs,
    measureViewportOnce,
    handleLiveInputAccessoryBytes,
    pendingDiffNotesDelivery,
    showCreateTabDrawer,
    insets,
    toastOpacityRef,
    runAcceptedMobileSessionTabsEffects: acceptedEffects = runAcceptedMobileSessionTabsEffects
  } = context
  const {
    readMarkdownTab,
    readFileTab,
    loadDiffComments,
    persistDiffComments,
    addDiffCommentForFile,
    deleteDiffCommentForFile,
    copyDiffCommentsToClipboard,
    sendDiffCommentsToAgent,
    clearDeliveredDiffComments,
    updateMarkdownLocalContent,
    copyMarkdownLocalContent,
    getDirtyMarkdownDrafts,
    leaveSession,
    requestLeaveSession,
    discardMarkdownLocalContent,
    confirmDiscardMarkdown,
    saveMarkdownTab
  } = useMobileSessionDocumentActions({
    client,
    setMarkdownDocs,
    worktreeId,
    setFileDocs,
    connState,
    isFloatingWorkspaceRoute,
    setDiffComments,
    diffCommentsRef,
    diffCommentBusy,
    setDiffCommentBusy,
    showToast,
    setPendingDiffNotesDelivery,
    markdownDocs,
    setLeaveDrafts,
    setDiscardMarkdownTarget,
    discardMarkdownTarget,
    markdownSaveInFlightRef,
    markdownSaveSeqRef,
    sessionTabs,
    router,
    hostId
  })

  const {
    consumeAcceptedSessionTabs,
    hasSessionTabsRecoveryNeed,
    getSessionTabsApplicationRevision,
    fetchSessionTabs,
    ensureSessionTabs,
    fetchPendingBrowserSessionTabs,
    hostQueryReplyInputSupportedRef,
    notifyTerminalFrameHeight,
    notifyKeyboardVisibility,
    scrollActiveTabIntoView,
    handleDeleteCustomKey,
    handleManageShortcuts
  } = useMobileSessionRecovery({
    runAcceptedMobileSessionTabsEffects: acceptedEffects,
    pendingBrowserFocusPageIdRef,
    switchSessionTabRef,
    setMarkdownDocs,
    closedTabTombstonesRef,
    appliedSessionTabsRevisionRef,
    appliedSnapshotMarkerRef,
    worktreeId,
    terminalDiagnosticsRef,
    client,
    connState,
    applySessionTabs,
    fetchTerminals,
    terminalGestureInputQueuesRef,
    terminalGestureInputInFlightRef,
    setBrowserScreencastSupported,
    setAgentSessionHistorySupported,
    setQuickCommandsSupported,
    setShowQuickCommands,
    setShowCustomKeyModal,
    startRuntimeCapabilityProbe,
    MOBILE_AI_VAULT_CAPABILITY,
    supportsMobileQuickCommands,
    TERMINAL_QUERY_REPLY_INPUT_RUNTIME_CAPABILITY,
    hostId,
    deviceTokenRef,
    setHostEndpoint,
    loadHosts,
    loadCustomKeys,
    setCustomKeys,
    loadTerminalAccessoryLayout,
    setVisibleBuiltInIds,
    terminalRefs,
    activeHandleRef,
    initializedHandlesRef,
    connStateRef,
    unsubscribeTerminal,
    subscribeToTerminal,
    scheduleDelayedAction,
    terminalFrameHeightRef,
    viewportRef,
    viewportMeasuredRef,
    clientRef,
    terminals,
    terminalTextScale,
    terminalFrameWidth,
    setKeyboardHeight,
    Keyboard,
    tabLayoutsRef,
    tabStripViewportWidthRef,
    tabStripContentWidthRef,
    tabStripOffsetRef,
    tabStripRef,
    resolveTabStripScrollOffset,
    activeSessionTabId,
    AsyncStorage,
    customKeys,
    saveCustomKeys,
    router,
    sessionTabActionSheetRequestSeqRef,
    sessionTabActionSheetKeyboardHideSubRef,
    clearTerminalCache,
    pendingActiveSessionTabIdRef,
    pendingActiveTerminalHandleRef,
    pendingTerminalActivationAttemptRef,
    initialSessionAutoCreateRef,
    createInitialSessionAutoCreateState,
    setActiveHandle,
    setTerminals,
    terminalsRef,
    setSessionTabs,
    setActiveSessionTabId,
    clearPendingLiveInputCommit,
    clearDelayedActionTimers,
    setTerminalsLoaded,
    created,
    isFloatingWorkspaceRoute,
    headlessActivationNeedsHostRenderer,
    showToast,
    loadTerminalTextScale,
    setTerminalTextScale,
    loadTerminalAutocompleteEnabled,
    setAutocompleteEnabled,
    loadTerminalLinkOpenMode,
    setTerminalLinkOpenMode
  })

  // Why: unsubscribe restores old dims (clears phone-fit banner); resubscribe phone-fits the new one.
  const {
    switchTab,
    switchSessionTab,
    setTerminalWebViewRef,
    handleTerminalWebReady,
    handleSend,
    handleAccessoryKey,
    sendLiveTerminalInput,
    focusLiveInput,
    clearSessionTabActionSheetKeyboardListener,
    openSessionTabActionSheet,
    openSessionTabActionSheetAfterKeyboardDismiss,
    dismissSoftwareKeyboard,
    handleTerminalTap,
    handleFileTapActivationSeqRef,
    handleFileTap,
    handleOpenedFileDiffActivationSeqRef,
    fileOpenStartActiveTabIdRef,
    handleFileOpenStart,
    handleOpenedFileDiff,
    handleTerminalOpenUrl
  } = useMobileSessionWorkspaceTerminalInteractions(context, { readFileTab, readMarkdownTab })

  const {
    toggleLiveInput,
    allowTerminalGestureInput,
    flushTerminalGestureInput,
    enqueueTerminalGestureInput,
    handleTerminalInput,
    handleTerminalQueryReply,
    handleClearTerminal,
    handleAccessoryKeyRef,
    stopAccessoryRepeat,
    startAccessoryRepeat,
    setMobileSessionRootRef,
    handleSelectionMode,
    handleSelectionCopy,
    handleSelectionEvicted,
    handleModesChanged,
    handleKeyboardAvoidanceMetrics,
    handleHaptic
  } = useMobileSessionTerminalInput({
    activeHandle,
    toggleTerminalLiveInput,
    clearPendingLiveInputCommit,
    scheduleTerminalLiveInputFocus,
    liveInputFocusTimerRef,
    clearTerminalLiveInputFocusTimer,
    liveInputRef,
    terminalGestureInputBucketsRef,
    TERMINAL_GESTURE_INPUT_BUCKET_CAPACITY,
    TERMINAL_GESTURE_INPUT_REFILL_PER_SECOND,
    terminalGestureInputQueuesRef,
    terminalGestureInputInFlightRef,
    activeHandleRef,
    activeSessionTabTypeRef,
    clientRef,
    connStateRef,
    buildTerminalSendParams,
    deviceTokenRef,
    TERMINAL_INPUT_SEND_OPTIONS,
    TERMINAL_GESTURE_INPUT_MAX_QUEUE_AGE_MS,
    TERMINAL_GESTURE_INPUT_MAX_PENDING_SEQUENCES,
    TERMINAL_GESTURE_INPUT_FLUSH_DELAY_MS,
    client,
    connState,
    ptyModesRef,
    isGestureMouseTrackingMode,
    countTerminalGestureInputSequences,
    sendMobileTerminalQueryReply,
    hostQueryReplyInputSupportedRef,
    terminalUnsubsRef,
    getTerminalRef,
    showToast,
    handleAccessoryKey,
    toastSeqRef,
    clearTerminalCache,
    clearToastHideTimer,
    clearDelayedActionTimers,
    sessionTabActionSheetRequestSeqRef,
    clearSessionTabActionSheetKeyboardListener,
    setSelectModeActive,
    terminalRefs,
    setTerminalKeyboardMetrics,
    initialModesSeenRef,
    triggerSelection,
    triggerSuccess,
    triggerError,
    triggerEdgeBump
  })

  const {
    getActiveWorktreeConnectionId,
    refreshCanPaste,
    handlePaste,
    attachImage,
    isAttaching,
    handleCreateTerminal
  } = useMobileSessionCreation({
    client,
    isFloatingWorkspaceRoute,
    worktreeId,
    getRepoIdFromMobileWorktreeId,
    setCanPaste,
    activeHandle,
    activeHandleRef,
    activeSessionTabTypeRef,
    canSend,
    connState,
    connStateRef,
    clientRef,
    deviceTokenRef,
    flushPendingLiveInputBeforeExternalSend,
    ptyModesRef,
    showToast,
    triggerError,
    triggerSelection,
    selectModeActive,
    terminalRefs,
    showCreateTabDrawer,
    pendingDiffNotesDelivery,
    setCreateTabAgentLoadState,
    setCreateTabAgentOptions,
    loadMobileNewTabAgentOptions,
    creatingTerminalRef,
    setCreating,
    setCreateError,
    activeSessionTab,
    unsubscribeTerminal,
    initializedHandlesRef,
    pendingActiveSessionTabIdRef,
    setActiveSessionTabId,
    setSessionTabs,
    defaultTerminalHandlesToLiveInput,
    pendingActiveTerminalHandleRef,
    setActiveHandle,
    setTerminals,
    terminalsRef,
    terminalRecordsEqual,
    subscribeToTerminal,
    scheduleDelayedAction,
    fetchSessionTabs,
    creatingMarkdown,
    creatingBrowser,
    browserScreencastSupportedRef,
    normalizeBrowserUrl,
    setCreatingMarkdown,
    setCreatingBrowser,
    fetchPendingBrowserSessionTabs,
    pendingBrowserFocusPageIdRef,
    setTerminalsLoaded,
    fetchTerminals,
    renameTarget,
    setRenameTarget,
    clearTerminalLiveInputDefault,
    terminals,
    sessionTabsRef,
    closedTabTombstonesRef,
    activeSessionTabIdRef
  })

  const {
    launchQuickCommand,
    handleCreateMarkdownNote,
    handleCreateBrowser,
    handleBrowserNavigationCommand,
    handleRenameTerminal,
    handleCloseTerminal,
    handleCloseSessionTab
  } = useMobileSessionActions({
    client,
    connState,
    creatingTerminalRef,
    creatingBrowser,
    creatingMarkdown,
    buildMobileQuickCommandLaunch,
    triggerError,
    showToast,
    handleCreateTerminal,
    setCreatingMarkdown,
    setCreateError,
    worktreeId,
    captureMobileFileMutationOwnership,
    isFileExistsErrorMessage,
    scheduleDelayedAction,
    fetchSessionTabs,
    setCreatingBrowser,
    browserScreencastSupportedRef,
    normalizeBrowserUrl,
    pendingBrowserFocusPageIdRef,
    fetchPendingBrowserSessionTabs,
    handleCreateBrowserRef,
    renameTarget,
    setRenameTarget,
    setTerminals,
    terminalsRef,
    fetchTerminals,
    unsubscribeTerminal,
    terminalRefs,
    initializedHandlesRef,
    clearTerminalLiveInputDefault,
    terminals,
    activeHandleRef,
    pendingActiveTerminalHandleRef,
    setActiveHandle,
    subscribeToTerminal,
    sessionTabsRef,
    setSessionTabs,
    closedTabTombstonesRef,
    activeSessionTabIdRef,
    activeSessionTabTypeRef,
    setActiveSessionTabId,
    defaultTerminalHandlesToLiveInput,
    pendingActiveSessionTabIdRef
  })

  const keyboardLift = keyboardHeight > 0 ? keyboardHeight : 0
  const toastAnimatedStyle = {
    opacity: toastOpacityRef.current,
    transform: [{ translateY: -keyboardLift }]
  }
  const createTabAgentActions =
    createTabAgentLoadState === 'loading'
      ? [{ label: 'Detecting Agents', icon: Bot, disabled: true, loading: true, onPress: () => {} }]
      : createTabAgentOptions.length > 0
        ? createTabAgentOptions.map((option: MobileNewTabAgentOption) => ({
            label: option.label,
            renderIcon: () => createElement(MobileAgentIcon, { agentId: option.agent, size: 16 }),
            onPress: () => {
              setShowCreateTabDrawer(false)
              void handleCreateTerminal(option.agent)
            }
          }))
        : createTabAgentLoadState === 'loaded'
          ? [{ label: 'No Enabled Agents', icon: Bot, disabled: true, onPress: () => {} }]
          : createTabAgentLoadState === 'error'
            ? [
                {
                  label: 'Agent Presets Unavailable',
                  hint: 'Check the host connection',
                  icon: Bot,
                  disabled: true,
                  onPress: () => {}
                }
              ]
            : []
  const sendDiffNotesAgentActions =
    pendingDiffNotesDelivery === null
      ? []
      : createTabAgentLoadState === 'loading'
        ? [
            {
              label: 'Detecting Agents',
              icon: Bot,
              disabled: true,
              loading: true,
              onPress: () => {}
            }
          ]
        : createTabAgentOptions.length > 0
          ? createTabAgentOptions.map((option: MobileNewTabAgentOption) => ({
              label: option.label,
              hint: 'New agent session',
              icon: Bot,
              onPress: () => {
                const delivery = pendingDiffNotesDelivery
                setPendingDiffNotesDelivery(null)
                if (!delivery) {
                  return
                }
                void handleCreateTerminal(option.agent, {
                  initialPrompt: delivery.prompt,
                  onPromptSent: () => void clearDeliveredDiffComments(delivery.comments)
                })
              }
            }))
          : createTabAgentLoadState === 'loaded'
            ? [{ label: 'No Enabled Agents', icon: Bot, disabled: true, onPress: () => {} }]
            : createTabAgentLoadState === 'error'
              ? [
                  {
                    label: 'Agent Presets Unavailable',
                    hint: 'Copy notes instead',
                    icon: Bot,
                    disabled: true,
                    onPress: () => {}
                  }
                ]
              : []
  const createTabBusy = creating || creatingBrowser || creatingMarkdown

  const bulkCloseActions = createBulkCloseSheetActions({
    sessionTabsRef,
    markdownDocs,
    activeSessionTabIdRef,
    switchSessionTab,
    closeSessionTab: handleCloseSessionTab
  })
  const closeWithBulkActions = createCloseWithBulkActions(handleCloseSessionTab, bulkCloseActions)

  return {
    ...context,
    ...{
      readMarkdownTab,
      readFileTab,
      loadDiffComments,
      persistDiffComments,
      addDiffCommentForFile,
      deleteDiffCommentForFile,
      copyDiffCommentsToClipboard,
      sendDiffCommentsToAgent,
      clearDeliveredDiffComments,
      updateMarkdownLocalContent,
      copyMarkdownLocalContent,
      getDirtyMarkdownDrafts,
      leaveSession,
      requestLeaveSession,
      discardMarkdownLocalContent,
      confirmDiscardMarkdown,
      saveMarkdownTab,
      consumeAcceptedSessionTabs,
      hasSessionTabsRecoveryNeed,
      getSessionTabsApplicationRevision,
      fetchSessionTabs,
      ensureSessionTabs,
      fetchPendingBrowserSessionTabs,
      hostQueryReplyInputSupportedRef,
      notifyTerminalFrameHeight,
      notifyKeyboardVisibility,
      scrollActiveTabIntoView,
      handleDeleteCustomKey,
      handleManageShortcuts,
      bulkCloseActions,
      closeWithBulkActions,
      handleCloseSessionTab,
      handleCloseTerminal,
      handleClearTerminal,
      handleRenameTerminal,
      handleBrowserNavigationCommand,
      handleFileOpenStart,
      handleOpenedFileDiff,
      handleCreateBrowser,
      handleCreateMarkdownNote,
      handleCreateTerminal,
      launchQuickCommand,
      setTerminalWebViewRef,
      handleTerminalWebReady,
      handleSelectionMode,
      handleSelectionCopy,
      handleSelectionEvicted,
      handleModesChanged,
      handleKeyboardAvoidanceMetrics,
      handleHaptic,
      handleTerminalInput,
      handleTerminalQueryReply,
      handleTerminalTap,
      handleFileTap,
      handleTerminalOpenUrl,
      handleDictationToggle,
      handleDictationPressIn,
      handleDictationPressOut,
      startDictation,
      cancelDictation,
      handleLiveInputChange,
      handleLiveInputKeyPress,
      handleLiveInputSubmit,
      handleSend,
      handlePaste,
      handleAccessoryKey,
      createTabAgentActions,
      sendDiffNotesAgentActions,
      isAttaching,
      toggleLiveInput,
      setMobileSessionRootRef,
      createTabBusy,
      keyboardLift,
      triggerSuccess,
      triggerError,
      getRepoIdFromMobileWorktreeId
    }
  }
}
