import { AGENTS, AUTOMATIONS_CHANGED_EVENT, DEFAULT_TIME, buildDraftPrecheck, buildHermesCronSchedule, formatExternalDate, formatTimeInput, getAgentLabel, getAutomationHostTargetFromKey, getAutomationHostTargetKey, getAutomationRunContent, getDefaultWorktree, getExternalAutomationKey, getExternalRunContent, getExternalRunStatusLabel, getExternalRunStatusVariant, getRepoBackedAutomationSourceContext, getRuntimeSourceHostAvailability, parseDraftTime, type AutomationPaneTab, type ExternalAutomationListEntry, type RepoBackedAutomationSourceContext } from './automations-page-orchestration-model';

import { waitForAutomationRerunPendingVisibility } from './automations-page-orchestration-actions';

/* Concrete automations page view and orchestration.
 * Form and detail presentation live in sibling files. */
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
 import { CalendarClock, Check, Clock, Eye, Pause, Pencil, Play, Plus, RefreshCw, Trash2, X } from 'lucide-react';
 import { toast } from 'sonner';
 import { filterEnabledTuiAgents, isTuiAgentEnabled } from '../../../../shared/tui-agent-selection';
 import type { Badge } from '@/components/ui/badge';
 import { Button } from '@/components/ui/button';
 import { installWindowVisibilityInterval } from '@/lib/window-visibility-interval';
 import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuSeparator, ContextMenuTrigger } from '@/components/ui/context-menu';
 import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
 import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
 import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
 import { useAppStore } from '@/store';
 import { callRuntimeRpc } from '@/runtime/runtime-rpc-client';
 import { getLocalPreflightContext, localPreflightContextKey } from '@/lib/local-preflight-context';
 import { cn } from '@/lib/utils';
 import RepoBadgeLabel from '@/components/repo/RepoBadgeLabel';
 import { getAgentCatalog } from '@/lib/agent-catalog';
 import { useRepoMap, useWorktreeMap } from '@/store/selectors';
 import { activateAndRevealWorktree } from '@/lib/worktree-activation';
import type { Automation, ExternalAutomationJob, ExternalAutomationManager, AutomationPrecheck, AutomationRun, AutomationUpdateInput } from '../../../../shared/automations-types';
 import { getAutomationRunRepoId } from '../../../../shared/automation-run-identity';
 import { getLocalExecutionHostLabel, getRepoExecutionHostId, parseExecutionHostId } from '../../../../shared/execution-host';
 import { getHostDisplayLabelOverrides } from '../../../../shared/host-setting-overrides';
 import { TASK_SOURCE_CONTEXT_RUNTIME_CAPABILITY } from '../../../../shared/protocol-version';
 import type { PreflightStatus } from '../../../../preload/api-types';
 import type { RuntimeStatus } from '../../../../shared/runtime-types';
 import type { TaskSourceContext } from '../../../../shared/task-source-context';
 import type { OrcaHooks, Repo, Worktree } from '../../../../shared/types';
 import { getWorktreePathBasenameFromId } from '../../../../shared/worktree-id';
 import { buildAutomationCronSchedule, buildAutomationRrule, formatAutomationSchedule, isValidAutomationCronSchedule, isValidAutomationSchedule, tryParseAutomationRrule } from '../../../../shared/automation-schedules';
 import { formatAutomationDateTimeWithRelative, getAutomationRunStatusLabel, getAutomationRunStatusVariant } from './automation-page-parts';
 import { formatAutomationCost, formatAutomationTokens, summarizeAutomationRunUsage } from './automation-usage-model';
 import { canRerunAutomationRun, getAutomationRunViewState } from './automation-run-view-state';
 import { automationRunMatchesPaneKey, buildAutomationRunOpenLayout, canOpenAutomationRunOpenTarget, getAutomationRunOpenTabId, resolveAutomationRunOpenTarget } from './automation-run-open-target';
 import { getAutomationRunWorkspaceDisplay } from './automation-run-workspace-display';
 import CommentMarkdown from '@/components/sidebar/CommentMarkdown';
 import { AutomationDetail } from './AutomationDetail';
 import { HermesCronOutputView } from './HermesCronOutputView';
 import { AutomationEditorDialog, type AutomationCreateTarget, type AutomationDraft } from './AutomationEditorDialog';
 import { AutomationRunPageFrame } from './AutomationRunPageFrame';
 import { AutomationRunHistory } from './AutomationRunHistory';
 import { getAutomationSetupDecisionDraftValue, getVisibleAutomationSetupDecision, resolveAutomationSetupDecisionForSave } from './automation-setup-decision';
 import { getAutomationTemplates, type AutomationTemplate } from './automation-templates';
 import { getAutomationTargetAvailability } from './automation-target-availability';
 import { buildAutomationRunContextForRepo } from './automation-run-context';
 import { ensureHooksConfirmed } from '@/lib/ensure-hooks-confirmed';
 import { getSettingsForRepoRuntimeOwner } from '@/lib/repo-runtime-owner';
 import { checkRuntimeHooks } from '@/runtime/runtime-hooks-client';
 import { getRepoBackedProviderAvailability, type RuntimeProviderPreflightStatus } from '../task-source-provider-availability';
 import type { TaskSourceHostAvailability } from '../task-source-context-summary';
 import { createAutomationForTarget, deleteAutomationForTarget, type AutomationHostTarget, getAutomationListTarget, getAutomationOwnerTarget, getAutomationTargetFromHostId, listAutomationRunsForTarget, listAutomationsForTarget, runAutomationNowForTarget, updateAutomationForTarget } from './automation-host-client';
 import { getExternalAutomationScheduleDisplay } from './external-automation-schedule-display';
 import { ExternalAutomationManagers } from './ExternalAutomationManagers';
import { useContextualTour } from '@/components/contextual-tours/use-contextual-tour';
import { translate } from '@/i18n/i18n';
import { AutomationsPageRenderer } from './automations-page-renderer'
import { buildExternalAutomationEditDraft, buildExternalAutomationEntries, getExternalAutomationSourceSelection, useExternalAutomationActions, useExternalAutomationState } from './automations-page-external-orchestration';
export default function AutomationsPage(): React.JSX.Element {;
 const repos = useAppStore((s) => s.repos);
 const projectHostSetups = useAppStore((s) => s.projectHostSetups);
 const worktreesByRepo = useAppStore((s) => s.worktreesByRepo);
 const unifiedTabsByWorktree = useAppStore((s) => s.unifiedTabsByWorktree);
 const terminalLayoutsByTabId = useAppStore((s) => s.terminalLayoutsByTabId);
 const ptyIdsByTabId = useAppStore((s) => s.ptyIdsByTabId);
 const activeWorktreeId = useAppStore((s) => s.activeWorktreeId);
 const fetchWorktrees = useAppStore((s) => s.fetchWorktrees);
 const fetchAllWorktrees = useAppStore((s) => s.fetchAllWorktrees);
 const startupWorktreeRefreshCompleted = useAppStore((s) => s.startupWorktreeRefreshCompleted);
 const updateSettings = useAppStore((s) => s.updateSettings);
 const openSettingsPage = useAppStore((s) => s.openSettingsPage);
 const openSettingsTarget = useAppStore((s) => s.openSettingsTarget);
 const closeAutomationsPage = useAppStore((s) => s.closeAutomationsPage);
 const agentStatusByPaneKey = useAppStore((s) => s.agentStatusByPaneKey);
 const retainedAgentsByPaneKey = useAppStore((s) => s.retainedAgentsByPaneKey);
 const sshConnectionStates = useAppStore((s) => s.sshConnectionStates);
 const sshTargetLabels = useAppStore((s) => s.sshTargetLabels);
 const runtimeEnvironments = useAppStore((s) => s.runtimeEnvironments);
 const runtimeStatusByEnvironmentId = useAppStore((s) => s.runtimeStatusByEnvironmentId);
 const settings = useAppStore((s) => s.settings);
 const preflightStatus = useAppStore((s) => s.preflightStatus);
 const preflightStatusChecked = useAppStore((s) => s.preflightStatusChecked);
 const preflightStatusContextKey = useAppStore((s) => s.preflightStatusContextKey);
 const refreshPreflightStatus = useAppStore((s) => s.refreshPreflightStatus);
 const expectedPreflightContextKey = useAppStore((s) => localPreflightContextKey(getLocalPreflightContext(s)) );
 const selectedId = useAppStore((s) => s.selectedAutomationId);
 const setSelectedId = useAppStore((s) => s.setSelectedAutomationId);
 const pendingAutomationRunNavigation = useAppStore((s) => s.pendingAutomationRunNavigation);
 const setPendingAutomationRunNavigation = useAppStore((s) => s.setPendingAutomationRunNavigation);
 const repoMap = useRepoMap();
 const worktreeMap = useWorktreeMap();
 const enabledAgents = filterEnabledTuiAgents(AGENTS, settings?.disabledTuiAgents);
 const defaultAgent = settings?.defaultTuiAgent && settings.defaultTuiAgent !== 'blank' && isTuiAgentEnabled(settings.defaultTuiAgent, settings.disabledTuiAgents) ? settings.defaultTuiAgent : (enabledAgents[0] ?? AGENTS[0]);
 const [automations, setAutomations] = useState<Automation[]>([]);
 const [runs, setRuns] = useState<AutomationRun[]>([]);
 const [automationHostTargetKey, setAutomationHostTargetKey] = useState<string | null>(null);
 const [selectedAutomationRuns, setSelectedAutomationRuns] = useState<{ automationId: string | null, runs: AutomationRun[] }>({ automationId: null, runs: [] });
 const { connectingExternalSourceKey, editingExternalTarget, externalActionKey, externalDeleteTarget, externalManagers, selectedExternalKey, selectedExternalRunPage, selectExternalKey, setConnectingExternalSourceKey, setEditingExternalTarget, setExternalActionKey, setExternalDeleteTarget, setExternalManagers, setSelectedExternalRunPage } = useExternalAutomationState();
 const [rerunRunIdsInFlight, setRerunRunIdsInFlight] = useState<ReadonlySet<string>>( () => new Set() );
 const [isLoading, setIsLoading] = useState(true);
 const [isSaving, setIsSaving] = useState(false);
 const [createOpen, setCreateOpen] = useState(false);
 const [createTarget, setCreateTarget] = useState<AutomationCreateTarget>('orca');
 const [editingAutomationId, setEditingAutomationId] = useState<string | null>(null);
 const [relativeNow, setRelativeNow] = useState(Date.now());
 const [activePaneTab, setActivePaneTab] = useState<AutomationPaneTab>('overview');
 const [selectedAutomationRunPageId, setSelectedAutomationRunPageId] = useState<string | null>( null );
 const runtimePreflightMountedRef = useRef(true);
 const runtimePreflightRequestedHostIdsRef = useRef<Set<TaskSourceContext['hostId']>>(new Set());
 const [runtimePreflightStatusByHostId, setRuntimePreflightStatusByHostId] = useState< ReadonlyMap<TaskSourceContext['hostId'], RuntimeProviderPreflightStatus> >(() => new Map());
 const selectAutomationId = useCallback( (automationId: string | null): void => { setSelectedAutomationRunPageId(null);
 setSelectedId(automationId) }, [setSelectedId] );
 const [draftAtOpen, setDraftAtOpen] = useState<AutomationDraft | null>(null);
 const [deleteTarget, setDeleteTarget] = useState<Automation | null>(null);
 useContextualTour( 'automations', !createOpen && !deleteTarget && !externalDeleteTarget, 'automations_open' );
 const [dontAskDeleteAgain, setDontAskDeleteAgain] = useState(false);
 const editRequestRef = useRef(0);
 const deleteConfirmButtonRef = useRef<HTMLButtonElement>(null);
 const completionInFlightRef = useRef<Set<string>>(new Set());
 const rerunRunIdsInFlightRef = useRef<Set<string>>(new Set());
 const workspaceNameCacheRef = useRef<Map<string, string>>(new Map());
 const setupDecisionPolicyDefaultRef = useRef<AutomationDraft['setupDecision']>(undefined);
 const setupDecisionDefaultSignatureRef = useRef<string | null>(null);
 const setupDecisionTouchedRef = useRef(false);
 const automationHookCheckPromisesRef = useRef< Map<string, Promise<{ hooks: OrcaHooks | null;
 ok: boolean }>> >(new Map());
 const [automationYamlHooksByRepoKey, setAutomationYamlHooksByRepoKey] = useState< Record<string, OrcaHooks | null> >({});
 const [draft, setDraft] = useState<AutomationDraft>({ name: '', prompt: '', agentId: defaultAgent, projectId: '', workspaceMode: 'existing', workspaceId: '', baseBranch: '', setupDecision: undefined, reuseSession: false, precheckCommand: '', precheckTimeoutSeconds: '60', preset: 'weekdays', time: DEFAULT_TIME, dayOfWeek: '1', customSchedule: '', missedRunGraceMinutes: '720', scheduleWarning: null });
 const externalAutomationEntries = useMemo<ExternalAutomationListEntry[]>( () => buildExternalAutomationEntries(externalManagers), [externalManagers] );
 const selectedExternal = externalAutomationEntries.find((entry) => entry.key === selectedExternalKey) ?? (automations.length === 0 ? (externalAutomationEntries[0] ?? null) : null);
 const selected = selectedExternal === null ? selectedId ? (automations.find((automation) => automation.id === selectedId) ?? null) : (automations[0] ?? null) : null;
 const runsWithWorkspaceNames = useMemo( () => runs.map((run) => {;
 if (!run.workspaceId || run.workspaceDisplayName?.trim()) {;
 return run };
 const displayName = worktreeMap.get(run.workspaceId)?.displayName ?? workspaceNameCacheRef.current.get(run.workspaceId) ?? getWorktreePathBasenameFromId(run.workspaceId);
 const trimmedDisplayName = displayName?.trim();
 return trimmedDisplayName ? { ...run, workspaceDisplayName: trimmedDisplayName } : run }), [runs, worktreeMap] );
 const selectedAutomationRunsWithWorkspaceNames = useMemo( () => selectedAutomationRuns.runs.map((run) => {;
 if (!run.workspaceId || run.workspaceDisplayName?.trim()) {;
 return run };
 const displayName = worktreeMap.get(run.workspaceId)?.displayName ?? workspaceNameCacheRef.current.get(run.workspaceId) ?? getWorktreePathBasenameFromId(run.workspaceId);
 const trimmedDisplayName = displayName?.trim();
 return trimmedDisplayName ? { ...run, workspaceDisplayName: trimmedDisplayName } : run }), [selectedAutomationRuns.runs, worktreeMap] );
 const getDraftSetupDecisionDefault = useCallback( ( candidate: Pick<AutomationDraft, 'projectId' | 'workspaceMode'> ): AutomationDraft['setupDecision'] => {;
 const settingsForRepo = getSettingsForRepoRuntimeOwner( { repos, settings }, candidate.projectId );
 const hookKey = `${settingsForRepo.activeRuntimeEnvironmentId ?? 'local'}:${candidate.projectId}`;
 return getVisibleAutomationSetupDecision({ createTarget, workspaceMode: candidate.workspaceMode, repoId: candidate.projectId, repos, projectHostSetups, yamlHooks: automationYamlHooksByRepoKey[hookKey] }) }, [automationYamlHooksByRepoKey, createTarget, projectHostSetups, repos, settings] );
 const getAutomationHooksCacheKey = useCallback( (repoId: string): string => {;
 const settingsForRepo = getSettingsForRepoRuntimeOwner({ repos, settings }, repoId);
 return `${settingsForRepo.activeRuntimeEnvironmentId ?? 'local'}:${repoId}` }, [repos, settings] );
 const loadAutomationYamlHooksForRepo = useCallback( async (repoId: string): Promise<OrcaHooks | null> => {;
 const key = getAutomationHooksCacheKey(repoId);
 if (Object.prototype.hasOwnProperty.call(automationYamlHooksByRepoKey, key)) {;
 return automationYamlHooksByRepoKey[key] ?? null };
 const existingPromise = automationHookCheckPromisesRef.current.get(key);
 if (existingPromise) {;
 return (await existingPromise).hooks };
 const settingsForRepo = getSettingsForRepoRuntimeOwner({ repos, settings }, repoId);
 const promise = checkRuntimeHooks(settingsForRepo, repoId) .then((result) => ({ hooks: result.status === 'error' ? null : ((result.hooks as OrcaHooks | null) ?? null), ok: result.status !== 'error' })) .catch(() => ({ hooks: null, ok: false }));
 automationHookCheckPromisesRef.current.set(key, promise);
 const { hooks, ok } = await promise;
 automationHookCheckPromisesRef.current.delete(key);
 if (!ok) {;
 return hooks };
 setAutomationYamlHooksByRepoKey((current) => Object.prototype.hasOwnProperty.call(current, key) ? current : { ...current, [key]: hooks } );
 return hooks }, [automationYamlHooksByRepoKey, getAutomationHooksCacheKey, repos, settings] );
 const getDraftSetupDecisionDefaultSignature = useCallback( (candidate: Pick<AutomationDraft, 'projectId' | 'workspaceMode'>): string => [ createTarget, candidate.workspaceMode, candidate.projectId, getDraftSetupDecisionDefault(candidate) ?? 'none' ].join(':'), [createTarget, getDraftSetupDecisionDefault] );
 const markSetupDecisionTouched = useCallback((): void => { setupDecisionTouchedRef.current = true }, []);
/* Why: keep the detail tab scoped even while the selected-run fetch catches up.*/ const selectedRunsSource = selected && selectedAutomationRuns.automationId === selected.id ? selectedAutomationRunsWithWorkspaceNames : runsWithWorkspaceNames;
 const selectedRuns = useMemo( () => (selected ? selectedRunsSource.filter((run) => run.automationId === selected.id) : []), [selected, selectedRunsSource] );
 const selectedAutomationRunPage = selectedAutomationRunPageId ? (selectedRuns.find((run) => run.id === selectedAutomationRunPageId) ?? null) : null;
 const worktrees = useMemo( () => worktreesByRepo[draft.projectId] ?? [], [draft.projectId, worktreesByRepo] );
 const automationHostTarget = useMemo( () => getAutomationHostTargetFromKey(automationHostTargetKey), [automationHostTargetKey] );
 useEffect(() => {;
 for (const [workspaceId, worktree] of worktreeMap) {;
 const displayName = worktree.displayName.trim();
 if (displayName) { workspaceNameCacheRef.current.set(workspaceId, displayName) } } }, [worktreeMap]);
 useEffect(() => {;
 if (!pendingAutomationRunNavigation || isLoading) {;
 return };
 const pending = pendingAutomationRunNavigation;
 const pendingTargetKey = getAutomationHostTargetKey( getAutomationTargetFromHostId(pending.hostId) );
 if (automationHostTargetKey !== pendingTargetKey) {;
 return };
 const pendingAutomation = automations.find( (automation) => automation.id === pending.automationId );
 if (!pendingAutomation) { /* Why: stale provenance should not silently select the first automation.*/ setSelectedId(pending.automationId);
 setSelectedAutomationRunPageId(null);
 setPendingAutomationRunNavigation(null);
 toast.message( translate( 'auto.components.automations.AutomationsPage.pendingAutomationMissing', 'Automation no longer available.' ) );
 return };
 if (selectedId !== pending.automationId) { setSelectedId(pending.automationId);
 return };
 if (!pending.runId) { setActivePaneTab('overview');
 setSelectedAutomationRunPageId(null);
 setPendingAutomationRunNavigation(null);
 return };
 if (selectedAutomationRuns.automationId !== pending.automationId) {;
 return };
 setActivePaneTab('runs');
 const pendingRun = selectedRuns.find((run) => run.id === pending.runId);
 if (pendingRun) { setSelectedAutomationRunPageId(pending.runId);
 setPendingAutomationRunNavigation(null);
 return };
 setSelectedAutomationRunPageId(null);
 setPendingAutomationRunNavigation(null);
 toast.message( translate( 'auto.components.automations.AutomationsPage.pendingAutomationRunMissing', 'Run history no longer available.' ) ) }, [ automations, automationHostTargetKey, isLoading, pendingAutomationRunNavigation, selectedAutomationRuns.automationId, selectedId, selectedRuns, setPendingAutomationRunNavigation, setSelectedId ]);
 const activeTerminalTabIds = useMemo(() => {;
 const ids = new Set<string>();
 for (const tabs of Object.values(unifiedTabsByWorktree)) {;
 for (const tab of tabs) {;
 if (tab.contentType === 'terminal') { ids.add(tab.entityId) } } };
 return ids }, [unifiedTabsByWorktree]);
 const selectedAutomationRunPageWorktree = selectedAutomationRunPage?.workspaceId ? (worktreeMap.get(selectedAutomationRunPage.workspaceId) ?? null) : null;
 const selectedAutomationRunPageWorkspaceDisplay = selectedAutomationRunPage ? getAutomationRunWorkspaceDisplay({ run: selectedAutomationRunPage, worktree: selectedAutomationRunPageWorktree }) : null;
 const selectedAutomationRunPageOpenTabId = selectedAutomationRunPage ? getAutomationRunOpenTabId(selectedAutomationRunPage) : null;
 const selectedAutomationRunPageViewState = selectedAutomationRunPage ? getAutomationRunViewState({ run: selectedAutomationRunPage, workspaceExists: Boolean(selectedAutomationRunPageWorktree), terminalTargetExists: canOpenAutomationRunOpenTarget({ run: selectedAutomationRunPage, terminalTabExists: selectedAutomationRunPageOpenTabId ? activeTerminalTabIds.has(selectedAutomationRunPageOpenTabId) : false, currentLayout: selectedAutomationRunPageOpenTabId ? terminalLayoutsByTabId[selectedAutomationRunPageOpenTabId] : null, livePtyIds: selectedAutomationRunPageOpenTabId ? (ptyIdsByTabId[selectedAutomationRunPageOpenTabId] ?? []) : [] }) }) : null;
 const canRerunSelectedAutomationRunPage = selectedAutomationRunPage !== null && canRerunAutomationRun({ automation: selected, run: selectedAutomationRunPage });
 const isSelectedAutomationRunPageRerunPending = selectedAutomationRunPage !== null && rerunRunIdsInFlight.has(selectedAutomationRunPage.id);
 const preflightStatusCurrent = preflightStatusContextKey === expectedPreflightContextKey;
 const repoBackedAutomationSourceContexts = useMemo( () => automations .map((automation) => getRepoBackedAutomationSourceContext(automation)) .filter((context): context is RepoBackedAutomationSourceContext => context !== null), [automations] );
 const runtimeAutomationSourceHostIds = useMemo(() => {;
 const hostIds = new Set<TaskSourceContext['hostId']>();
 for (const context of repoBackedAutomationSourceContexts) {;
 const parsed = parseExecutionHostId(context.hostId);
 if (parsed?.kind !== 'runtime') { continue };
 const hostAvailability = getRuntimeSourceHostAvailability( context, runtimeStatusByEnvironmentId );
 if (hostAvailability) { continue };
 hostIds.add(parsed.id) };
 return [...hostIds].sort() }, [repoBackedAutomationSourceContexts, runtimeStatusByEnvironmentId]);
 useEffect( () => () => { runtimePreflightMountedRef.current = false }, [] );
 useEffect(() => {;
 if (!preflightStatusCurrent || !preflightStatusChecked) { void refreshPreflightStatus() } }, [preflightStatusChecked, preflightStatusCurrent, refreshPreflightStatus]);
 useEffect(() => {;
 const unrequestedHostIds = runtimeAutomationSourceHostIds.filter( (hostId) => !runtimePreflightRequestedHostIdsRef.current.has(hostId) );
 if (unrequestedHostIds.length === 0) {;
 return };
 setRuntimePreflightStatusByHostId((current) => {;
 const next = new Map(current);
 for (const hostId of unrequestedHostIds) { next.set(hostId, { checked: false, status: null }) };
 return next });
 for (const hostId of unrequestedHostIds) { runtimePreflightRequestedHostIdsRef.current.add(hostId);
 const parsed = parseExecutionHostId(hostId);
 if (parsed?.kind !== 'runtime') { continue } /* Why: automation sources can be owned by a different remote server than*/ /* the run target;
 provider auth/tooling must be checked on the source host.*/ void callRuntimeRpc<PreflightStatus>( { kind: 'environment', environmentId: parsed.environmentId }, 'preflight.check', undefined, { timeoutMs: 15_000 } ) .then((status) => {;
 if (!runtimePreflightMountedRef.current) {;
 return };
 setRuntimePreflightStatusByHostId((current) => {;
 const next = new Map(current);
 next.set(hostId, { checked: true, status });
 return next }) }) .catch(() => {;
 if (!runtimePreflightMountedRef.current) {;
 return };
 setRuntimePreflightStatusByHostId((current) => {;
 const next = new Map(current);
 next.set(hostId, { checked: true, status: null });
 return next }) }) } }, [runtimeAutomationSourceHostIds]);
 const automationSourceHostAvailabilityById = useMemo(() => {;
 const availabilityById = new Map<string, TaskSourceHostAvailability[]>();
 for (const automation of automations) {;
 const context = getRepoBackedAutomationSourceContext(automation);
 if (!context) { continue };
 const hostAvailability = getRuntimeSourceHostAvailability( context, runtimeStatusByEnvironmentId );
 const providerAvailability = getRepoBackedProviderAvailability({ provider: context.provider, contexts: [context], preflightStatus, preflightReady: preflightStatusCurrent && preflightStatusChecked, runtimePreflightStatusByHostId });
 const availability = [ ...(hostAvailability ? [hostAvailability] : []), ...providerAvailability ];
 if (availability.length > 0) { availabilityById.set(automation.id, availability) } };
 return availabilityById }, [ automations, preflightStatus, preflightStatusChecked, preflightStatusCurrent, runtimePreflightStatusByHostId, runtimeStatusByEnvironmentId ]);
 const selectedRepo = selected ? (repoMap.get(getAutomationRunRepoId(selected)) ?? null) : null;
 const selectedWorktree = selected && selected.workspaceId ? (worktreeMap.get(selected.workspaceId) ?? null) : null;
 const selectedRunNowAvailability = selected ? getAutomationTargetAvailability({ automation: selected, repo: selectedRepo, workspace: selectedWorktree, projectHostSetups, sshConnectionStates, runtimeStatusByEnvironmentId, automationHostTarget, sourceHostAvailability: automationSourceHostAvailabilityById.get(selected.id) }) : null;
 const canSaveDraft = editingAutomationId === null || !draftAtOpen || JSON.stringify(draft) !== JSON.stringify(draftAtOpen);
 const { selectedExternalSshSource, selectedExternalSshStatus, selectedExternalSshConnected, isSelectedExternalSshConnecting, selectedExternalSourceAvailability } = getExternalAutomationSourceSelection({ connectingExternalSourceKey, selectedExternal, sshConnectionStates });
 const getAutomationRepoHostLabel = useCallback( (repo: Repo): string => {;
 const hostId = getRepoExecutionHostId(repo);
 const parsed = parseExecutionHostId(hostId);
 if (parsed?.kind === 'ssh') {;
 return sshTargetLabels.get(parsed.targetId) ?? parsed.targetId };
 if (parsed?.kind === 'runtime') {;
 return ( runtimeEnvironments.find((environment) => environment.id === parsed.environmentId) ?.name ?? parsed.environmentId ) };
 return getLocalExecutionHostLabel() }, [runtimeEnvironments, sshTargetLabels] );
 const hostLabelOverrides = useMemo(() => getHostDisplayLabelOverrides(settings), [settings]);
 const hostLabelById = useMemo(() => {;
 const labels = new Map<string, string>([['local', getLocalExecutionHostLabel()]]);
 for (const [targetId, label] of sshTargetLabels) { labels.set(`ssh:${encodeURIComponent(targetId)}`, label) };
 for (const environment of runtimeEnvironments) { labels.set(`runtime:${encodeURIComponent(environment.id)}`, environment.name) };
 for (const [hostId, label] of hostLabelOverrides) { labels.set(hostId, label) };
 return labels }, [hostLabelOverrides, runtimeEnvironments, sshTargetLabels]);
 useEffect(() => {;
 if ((!selected || selectedExternal) && activePaneTab === 'runs') { setActivePaneTab('overview') } }, [activePaneTab, selected, selectedExternal]);
 const getDefaultTarget = useCallback(() => {;
 const activeWorktree = activeWorktreeId ? worktreeMap.get(activeWorktreeId) : null;
 const activeRepo = activeWorktree ? (repoMap.get(activeWorktree.repoId) ?? null) : null;
 const fallbackRepo = activeRepo ?? repos[0] ?? null;
 const fallbackWorktrees = fallbackRepo ? (worktreesByRepo[fallbackRepo.id] ?? []) : [];
/* Why: automation-created workspaces can be active;
 new automations should start from*/ /* the repo's stable main worktree unless the user explicitly chooses otherwise.*/ const targetWorktree = getDefaultWorktree(fallbackWorktrees) ?? activeWorktree;
 const targetProjectId = fallbackRepo?.id ?? targetWorktree?.repoId ?? '';
 return { projectId: targetProjectId, workspaceId: targetWorktree?.id ?? '' } }, [activeWorktreeId, repoMap, repos, worktreeMap, worktreesByRepo]);
 const refresh = useCallback(async () => { setIsLoading(true);
 const pendingNavigation = useAppStore.getState().pendingAutomationRunNavigation;
 const automationHostTarget = pendingNavigation ? getAutomationTargetFromHostId(pendingNavigation.hostId) : getAutomationListTarget(settings);
 try {;
 const [nextAutomations, nextRuns, nextExternalManagers] = await Promise.all([ listAutomationsForTarget(automationHostTarget), listAutomationRunsForTarget(automationHostTarget), window.api.automations.listExternalManagers() ]);
 const currentSelectedId = useAppStore.getState().selectedAutomationId;
 const hasCurrentSelection = nextAutomations.some( (automation) => automation.id === currentSelectedId );
 let nextSelectedId: string | null;
 if (hasCurrentSelection) { nextSelectedId = currentSelectedId } else if (pendingNavigation) { nextSelectedId = pendingNavigation.automationId } else { nextSelectedId = nextAutomations[0]?.id ?? null };
 const nextSelectedRuns = nextSelectedId ? await listAutomationRunsForTarget(automationHostTarget, nextSelectedId) : [];
 setAutomations(nextAutomations);
 setRuns(nextRuns);
 setAutomationHostTargetKey(getAutomationHostTargetKey(automationHostTarget));
 setSelectedAutomationRuns({ automationId: nextSelectedId, runs: nextSelectedRuns });
 setExternalManagers(nextExternalManagers);
 if (!hasCurrentSelection && !pendingNavigation) { selectAutomationId(nextAutomations[0]?.id ?? null) } } finally { setIsLoading(false) } }, [selectAutomationId, settings]);
 const { confirmDeleteExternalAutomation, connectExternalAutomationSource, fetchExternalAutomationRuns, openExternalRunPage, requestExternalAction } = useExternalAutomationActions({ externalDeleteTarget, refresh, setConnectingExternalSourceKey, setExternalActionKey, setExternalDeleteTarget, setSelectedExternalRunPage, sshConnectionStates });
 useEffect(() => {;
 if (!pendingAutomationRunNavigation || isLoading) {;
 return };
 const pendingTargetKey = getAutomationHostTargetKey( getAutomationTargetFromHostId(pendingAutomationRunNavigation.hostId) );
 if (automationHostTargetKey !== pendingTargetKey) { void refresh() } }, [automationHostTargetKey, isLoading, pendingAutomationRunNavigation, refresh]);
 const hydratePersistedUIState = useCallback(async (): Promise<void> => { useAppStore.getState().hydratePersistedUI(await window.api.ui.get(), 'sync') }, []);
 const mountedBeforeStartupWorktreeRefreshRef = useRef(!startupWorktreeRefreshCompleted);
 useEffect(() => {;
 if (!startupWorktreeRefreshCompleted) {;
 return };
 if (mountedBeforeStartupWorktreeRefreshRef.current) { /* Why: App just supplied this mount's initial worktrees;
 a second full scan would duplicate every repo probe.*/ mountedBeforeStartupWorktreeRefreshRef.current = false;
 return } void fetchAllWorktrees() }, [fetchAllWorktrees, startupWorktreeRefreshCompleted]);
 useEffect(() => { void refresh() }, [refresh]);
 useEffect(() => { /* Pause the relative-time clock while the window is hidden.*/ return installWindowVisibilityInterval({ run: () => setRelativeNow(Date.now()), intervalMs: 60 * 1000 }) }, []);
 useEffect(() => {;
 const automationId = selected?.id ?? null;
 if (!automationId) { setSelectedAutomationRuns({ automationId: null, runs: [] });
 return };
 let cancelled = false;
 const target = pendingAutomationRunNavigation?.automationId === automationId && pendingAutomationRunNavigation.hostId ? getAutomationTargetFromHostId(pendingAutomationRunNavigation.hostId) : selected ? getAutomationOwnerTarget(selected, automationHostTarget) : getAutomationListTarget(settings);
 void listAutomationRunsForTarget(target, automationId).then((nextRuns) => {;
 if (!cancelled) { setSelectedAutomationRuns({ automationId, runs: nextRuns }) } });
 return () => { cancelled = true } }, [automationHostTarget, pendingAutomationRunNavigation, selected, selected?.id, runs, settings]);
 useEffect(() => {;
 const onAutomationsChanged = (): void => { void refresh() };
 window.addEventListener(AUTOMATIONS_CHANGED_EVENT, onAutomationsChanged);
 return () => window.removeEventListener(AUTOMATIONS_CHANGED_EVENT, onAutomationsChanged) }, [refresh]);
 useEffect(() => {;
 const onVisibilityOrFocus = (): void => {;
 if (document.visibilityState === 'visible') { void refresh() } };
 window.addEventListener('focus', onVisibilityOrFocus);
 document.addEventListener('visibilitychange', onVisibilityOrFocus);
 return () => { window.removeEventListener('focus', onVisibilityOrFocus);
 document.removeEventListener('visibilitychange', onVisibilityOrFocus) } }, [refresh]);
 useEffect(() => {;
 const inFlight = completionInFlightRef.current;
 const completedRuns = runs.filter((run) => {;
 if (run.status !== 'dispatched' || !run.terminalPaneKey) {;
 return false };
 if (inFlight.has(run.id)) {;
 return false };
 const dispatchedAt = run.dispatchedAt ?? null;
 if (dispatchedAt === null) {;
 return false };
 const liveDone = Object.entries(agentStatusByPaneKey).some( ([paneKey, entry]) => automationRunMatchesPaneKey(run, paneKey) && entry.state === 'done' && entry.updatedAt >= dispatchedAt );
 if (liveDone) {;
 return true };
 return Object.entries(retainedAgentsByPaneKey).some( ([paneKey, retained]) => automationRunMatchesPaneKey(run, paneKey) && retained.entry.state === 'done' && retained.entry.updatedAt >= dispatchedAt ) });
 if (completedRuns.length === 0) {;
 return };
 for (const run of completedRuns) { inFlight.add(run.id) } void Promise.all( completedRuns.map((run) => window.api.automations.markDispatchResult({ runId: run.id, status: 'completed', workspaceId: run.workspaceId, terminalSessionId: run.terminalSessionId, terminalPaneKey: run.terminalPaneKey, terminalPtyId: run.terminalPtyId, error: null }) ) ) .then(() => refresh()) .catch((error) => { console.error('[automations] failed to mark completed dispatch result:', error) }) .finally(() => {;
 for (const run of completedRuns) { inFlight.delete(run.id) } }) }, [agentStatusByPaneKey, retainedAgentsByPaneKey, refresh, runs]);
 useEffect(() => {;
 if (!draft.projectId) {;
 const target = getDefaultTarget();
 if (!target.projectId) {;
 return };
 setDraft((current) => ({ ...current, projectId: target.projectId, workspaceId: target.workspaceId })) } }, [draft.projectId, getDefaultTarget]);
 useEffect(() => {;
 if (!draft.projectId) {;
 return };
 const available = worktreesByRepo[draft.projectId] ?? [];
 const defaultWorktree = getDefaultWorktree(available);
 if (!draft.workspaceId && defaultWorktree) { setDraft((current) => ({ ...current, workspaceId: defaultWorktree.id })) } }, [draft.projectId, draft.workspaceId, worktreesByRepo]);
 useEffect(() => {;
 if ( !createOpen || createTarget !== 'orca' || draft.workspaceMode !== 'new_per_run' || !draft.projectId ) {;
 return } void loadAutomationYamlHooksForRepo(draft.projectId) }, [ createOpen, createTarget, draft.projectId, draft.workspaceMode, loadAutomationYamlHooksForRepo ]);
 useEffect(() => {;
 if (!createOpen) { setupDecisionPolicyDefaultRef.current = undefined;
 setupDecisionDefaultSignatureRef.current = null;
 setupDecisionTouchedRef.current = false;
 return };
 const nextDefault = getDraftSetupDecisionDefault(draft);
 const nextSignature = getDraftSetupDecisionDefaultSignature(draft);
 if (setupDecisionDefaultSignatureRef.current !== nextSignature) { setupDecisionDefaultSignatureRef.current = nextSignature;
 setupDecisionTouchedRef.current = false };
 const previousDefault = setupDecisionPolicyDefaultRef.current;
 setupDecisionPolicyDefaultRef.current = nextDefault;
 const shouldApplyPolicyDefault = !setupDecisionTouchedRef.current && (nextDefault === undefined || draft.setupDecision === undefined || draft.setupDecision === previousDefault);
 if (!shouldApplyPolicyDefault || draft.setupDecision === nextDefault) {;
 return };
 setDraft((current) => ({ ...current, setupDecision: nextDefault })) }, [createOpen, draft, getDraftSetupDecisionDefault, getDraftSetupDecisionDefaultSignature]);
 const applyTemplateToDraft = useCallback((template: AutomationTemplate): void => { setDraft((current) => ({ ...current, name: template.name, prompt: template.prompt, preset: template.preset, time: template.time ?? current.time, dayOfWeek: template.dayOfWeek ?? current.dayOfWeek, customSchedule: '', agentId: template.agentId ?? current.agentId, missedRunGraceMinutes: template.missedRunGraceMinutes ?? current.missedRunGraceMinutes, scheduleWarning: null })) }, []);
 const handleCreateTargetChange = useCallback((target: AutomationCreateTarget): void => { setCreateTarget(target);
 if (target === 'hermes') { setDraft((current) => ({ ...current, agentId: 'hermes', workspaceMode: 'existing', setupDecision: undefined, reuseSession: false })) } }, []);
 const openCreateDialog = (template?: AutomationTemplate): void => { editRequestRef.current += 1;
 const target = getDefaultTarget();
 setEditingAutomationId(null);
 setEditingExternalTarget(null);
 setCreateTarget('orca');
 const baseDraft: AutomationDraft = { name: '', prompt: '', agentId: defaultAgent, projectId: target.projectId, workspaceMode: 'existing', workspaceId: target.workspaceId, baseBranch: '', setupDecision: undefined, reuseSession: false, precheckCommand: '', precheckTimeoutSeconds: '60', preset: 'weekdays', time: DEFAULT_TIME, dayOfWeek: '1', customSchedule: '', missedRunGraceMinutes: '720', scheduleWarning: null };
 const nextDraft = template ? { ...baseDraft, name: template.name, prompt: template.prompt, preset: template.preset, time: template.time ?? baseDraft.time, dayOfWeek: template.dayOfWeek ?? baseDraft.dayOfWeek, customSchedule: '', agentId: template.agentId ?? baseDraft.agentId, missedRunGraceMinutes: template.missedRunGraceMinutes ?? baseDraft.missedRunGraceMinutes } : baseDraft;
 setDraft(nextDraft);
 setDraftAtOpen(nextDraft);
 setCreateOpen(true) };
 const openEditDialog = async (automation: Automation): Promise<void> => {;
 const requestId = (editRequestRef.current += 1);
 setEditingExternalTarget(null);
 setCreateTarget('orca');
 let latest = automation;
 try { latest = (await window.api.automations.list()).find((entry) => entry.id === automation.id) ?? automation } catch { latest = automation };
 if (requestId !== editRequestRef.current) {;
 return };
 const schedule = tryParseAutomationRrule(latest.rrule);
 const hasCustomSchedule = !schedule && isValidAutomationSchedule(latest.rrule);
 setEditingAutomationId(latest.id);
 const nextDraft: AutomationDraft = { name: latest.name, prompt: latest.prompt, agentId: latest.agentId, projectId: getAutomationRunRepoId(latest), workspaceMode: latest.workspaceMode, workspaceId: latest.workspaceId ?? '', baseBranch: latest.baseBranch ?? '', setupDecision: getAutomationSetupDecisionDraftValue({ workspaceMode: latest.workspaceMode, persistedSetupDecision: latest.setupDecision }), reuseSession: latest.workspaceMode === 'existing' && latest.reuseSession, precheckCommand: latest.precheck?.command ?? '', precheckTimeoutSeconds: String(latest.precheck?.timeoutSeconds ?? 60), preset: schedule?.preset ?? (hasCustomSchedule ? 'custom' : 'weekdays'), time: schedule ? formatTimeInput(schedule.hour, schedule.minute) : DEFAULT_TIME, dayOfWeek: String(schedule?.dayOfWeek ?? 1), customSchedule: hasCustomSchedule ? latest.rrule : '', missedRunGraceMinutes: String(latest.missedRunGraceMinutes), scheduleWarning: schedule || hasCustomSchedule ? null : 'This automation has an unsupported saved schedule. Pick a supported schedule before saving changes.' };
 setDraft(nextDraft);
 setDraftAtOpen(nextDraft);
 setCreateOpen(true) };
 const openEditExternalDialog = ( manager: ExternalAutomationManager, job: ExternalAutomationJob ): void => { editRequestRef.current += 1;
 const nextDraft = buildExternalAutomationEditDraft({ manager, job, repoMap, worktreesByRepo, fallbackTarget: getDefaultTarget() });
 setEditingAutomationId(null);
 setEditingExternalTarget({ manager, job });
 setCreateTarget('hermes');
 setDraft(nextDraft);
 setDraftAtOpen(nextDraft);
 setCreateOpen(true) };
 const handleProjectChange = useCallback( (projectId: string): void => {;
 const currentWorktrees = worktreesByRepo[projectId] ?? [];
 const currentDefaultWorktree = getDefaultWorktree(currentWorktrees);
 setDraft((current) => ({ ...current, projectId, workspaceId: currentDefaultWorktree?.id ?? '', baseBranch: '' }));
 void fetchWorktrees(projectId).then(() => {;
 const latestWorktrees = useAppStore.getState().worktreesByRepo[projectId] ?? [];
 const latestWorktree = getDefaultWorktree(latestWorktrees);
 if (!latestWorktree) {;
 return } /* Why: project worktrees may not be loaded when the repo picker changes.*/ /* Select after fetching so saving does not fail on an empty workspace id.*/ setDraft((current) => current.projectId === projectId && !current.workspaceId ? { ...current, workspaceId: latestWorktree.id } : current ) }) }, [fetchWorktrees, worktreesByRepo] );
 const saveAutomation = async (): Promise<void> => {;
 const { hour, minute } = parseDraftTime(draft.time);
 const isHermesSave = editingAutomationId === null && (createTarget === 'hermes' || editingExternalTarget !== null);
 if ( !draft.projectId || ((draft.workspaceMode === 'existing' || isHermesSave) && !draft.workspaceId) || !draft.prompt.trim() ) { toast.error( translate( 'auto.components.automations.AutomationsPage.2430fecf53', 'Choose a run location and enter a prompt before saving.' ) );
 return };
 if (draft.scheduleWarning) { toast.error( translate( 'auto.components.automations.AutomationsPage.64bdb2304f', 'Pick a supported schedule before saving.' ) );
 return };
 const validateAdvancedSchedule = isHermesSave ? isValidAutomationCronSchedule : isValidAutomationSchedule;
 if (draft.preset === 'custom' && !validateAdvancedSchedule(draft.customSchedule)) { toast.error( translate( 'auto.components.automations.AutomationsPage.6e91dab317', 'Enter a valid advanced schedule before saving.' ) );
 return };
 if ( editingAutomationId === null && !isHermesSave && !isTuiAgentEnabled(draft.agentId, settings?.disabledTuiAgents) ) { toast.error( translate( 'auto.components.automations.AutomationsPage.2360ffc956', 'Choose an enabled agent before saving.' ) );
 return };
 setIsSaving(true);
 try {;
 const selectedWorkspaceExists = draft.workspaceMode !== 'existing' || worktrees.some((worktree) => worktree.id === draft.workspaceId);
 if (!selectedWorkspaceExists) { toast.error( translate( 'auto.components.automations.AutomationsPage.32534e7c9c', 'Choose an available workspace before saving.' ) );
 return };
 if (isHermesSave) {;
 const repo = repoMap.get(draft.projectId);
 const selectedWorktree = worktreeMap.get(draft.workspaceId) ?? null;
 if (!repo || !selectedWorktree) { toast.error( translate( 'auto.components.automations.AutomationsPage.32534e7c9c', 'Choose an available workspace before saving.' ) );
 return };
 const target = editingExternalTarget?.manager.target ?? (repo.connectionId ? { type: 'ssh' as const, connectionId: repo.connectionId } : { type: 'local' as const });
 const repoTargetMatches = target.type === 'local' ? !repo.connectionId : repo.connectionId === target.connectionId;
 if (!repoTargetMatches) { toast.error( translate( 'auto.components.automations.AutomationsPage.e431bb85d4', 'Choose a workspace on the same host as this Hermes automation.' ) );
 return };
 const schedule = buildHermesCronSchedule(draft);
 const managerId = editingExternalTarget?.manager.id ?? (target.type === 'ssh' ? `hermes:ssh:${target.connectionId}` : 'hermes:local');
 const input = { managerId, provider: 'hermes' as const, target, name: draft.name, prompt: draft.prompt, schedule, workdir: selectedWorktree.path };
 await (editingExternalTarget ? window.api.automations.updateExternal({ ...input, jobId: editingExternalTarget.job.id }) : window.api.automations.createExternal(input));
 if (!editingExternalTarget) { useAppStore.getState().recordFeatureInteraction('automation-created') };
await refresh();
 setCreateOpen(false);
 setEditingExternalTarget(null);
 selectExternalKey( editingExternalTarget ? getExternalAutomationKey(editingExternalTarget.manager, editingExternalTarget.job) : null );
 toast.success( editingExternalTarget ? translate( 'auto.components.automations.AutomationsPage.08efc3ae12', 'Hermes automation updated.' ) : translate( 'auto.components.automations.AutomationsPage.77b81bc4ac', 'Hermes automation created.' ) );
 return };
 const now = Date.now();
 const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
 const rrule = draft.preset === 'custom' ? draft.customSchedule.trim() : buildAutomationRrule({ preset: draft.preset, hour, minute, dayOfWeek: Number(draft.dayOfWeek) });
 const rawMissedRunGraceMinutes = Number(draft.missedRunGraceMinutes);
 const missedRunGraceMinutes = Number.isFinite(rawMissedRunGraceMinutes) ? Math.max(0, rawMissedRunGraceMinutes) : 720;
 const precheck = buildDraftPrecheck(draft);
 const runContext = buildAutomationRunContextForRepo({ repoId: draft.projectId, repos, projectHostSetups });
 let setupDecision = resolveAutomationSetupDecisionForSave({ createTarget, workspaceMode: draft.workspaceMode, repoId: draft.projectId, repos, projectHostSetups, yamlHooks: createTarget === 'orca' && draft.workspaceMode === 'new_per_run' ? await loadAutomationYamlHooksForRepo(draft.projectId) : null, draftSetupDecision: draft.setupDecision });
 if (setupDecision === 'run') {;
 const trustDecision = await ensureHooksConfirmed( useAppStore.getState(), draft.projectId, 'setup' );
 if (trustDecision === 'skip') { setupDecision = 'skip' } };
 if (!runContext) { toast.error( translate( 'auto.components.automations.AutomationsPage.32534e7c9c', 'Choose an available workspace before saving.' ) );
 return };
 let currentAutomation = editingAutomationId ? (automations.find((automation) => automation.id === editingAutomationId) ?? null) : null;
 if (editingAutomationId) {;
 try { currentAutomation = (await listAutomationsForTarget(getAutomationListTarget(settings))).find( (automation) => automation.id === editingAutomationId ) ?? currentAutomation } catch { /* Keep the in-memory automation as a fallback if the refresh fails.*/ } };
 const updates: AutomationUpdateInput = { name: draft.name, prompt: draft.prompt, precheck, agentId: draft.agentId, runContext, projectId: draft.projectId, workspaceMode: draft.workspaceMode, workspaceId: draft.workspaceId, baseBranch: draft.baseBranch.trim() || null, setupDecision, reuseSession: draft.workspaceMode === 'existing' && draft.reuseSession, timezone, missedRunGraceMinutes };
 if (!currentAutomation || currentAutomation.rrule !== rrule) { /* Why: non-schedule edits should not reset dtstart or move nextRunAt.*/ updates.rrule = rrule;
 updates.dtstart = now };
 const automation = editingAutomationId ? currentAutomation ? await updateAutomationForTarget(currentAutomation, updates, automationHostTarget) : await window.api.automations.update({ id: editingAutomationId, updates }) : await createAutomationForTarget({ name: draft.name, prompt: draft.prompt, precheck, agentId: draft.agentId, runContext, projectId: draft.projectId, workspaceMode: draft.workspaceMode, workspaceId: draft.workspaceId, baseBranch: draft.baseBranch.trim() || null, setupDecision, reuseSession: draft.workspaceMode === 'existing' && draft.reuseSession, timezone, rrule, dtstart: now, missedRunGraceMinutes });
 if (!editingAutomationId) { await hydratePersistedUIState() };
 setAutomations((current) => {;
 const next = current.filter((entry) => entry.id !== automation.id);
 return [...next, automation].sort((left, right) => left.name.localeCompare(right.name)) });
 setDraft((current) => ({ ...current, name: '', prompt: '' }));
await refresh();
 selectAutomationId(automation.id);
 setCreateOpen(false);
 if (!editingAutomationId) { useAppStore.getState().recordFeatureInteraction('automation-created') };
 toast.success( editingAutomationId ? translate( 'auto.components.automations.AutomationsPage.244727e655', 'Automation updated.' ) : translate('auto.components.automations.AutomationsPage.2a20596d6b', 'Automation saved.') ) } catch (error) {;
 if (isHermesSave) { await refresh().catch(() => undefined) };
 toast.error( error instanceof Error ? error.message : translate( 'auto.components.automations.AutomationsPage.b11170a008', 'Failed to save automation.' ) ) } finally { setIsSaving(false) } };
 const toggleAutomation = async (automation: Automation): Promise<void> => { await updateAutomationForTarget( automation, { enabled: !automation.enabled }, automationHostTarget );
await refresh() };
 const deleteAutomation = async (automation: Automation): Promise<void> => { await deleteAutomationForTarget(automation, automationHostTarget);
 if (useAppStore.getState().selectedAutomationId === automation.id) { selectAutomationId(null) };
await refresh() };
 const persistDeleteAutomationPreference = (): void => { void updateSettings({ skipDeleteAutomationConfirm: true });
 toast.success( translate( 'auto.components.automations.AutomationsPage.690b94da54', "We'll skip this confirmation next time." ), { description: translate( 'auto.components.automations.AutomationsPage.d2a01b0b6f', 'You can change this in Settings.' ), duration: 8000, action: { label: translate( 'auto.components.automations.AutomationsPage.8a3226f172', 'Open Settings' ), onClick: () => { openSettingsPage();
 openSettingsTarget({ pane: 'general', repoId: null, sectionId: 'general-skip-delete-automation-confirm' }) } } } ) };
 const requestDeleteAutomation = (automation: Automation): void => {;
 if (settings?.skipDeleteAutomationConfirm) { void deleteAutomation(automation);
 return };
 setDontAskDeleteAgain(false);
 setDeleteTarget(automation) };
 const confirmDeleteAutomation = async (): Promise<void> => {;
 if (!deleteTarget) {;
 return };
 if (dontAskDeleteAgain) { persistDeleteAutomationPreference() };
 const target = deleteTarget;
 setDeleteTarget(null);
 setDontAskDeleteAgain(false);
await deleteAutomation(target) };
 const runNow = async (automation: Automation): Promise<void> => {;
 const repo = repoMap.get(getAutomationRunRepoId(automation)) ?? null;
 const workspace = automation.workspaceId ? (worktreeMap.get(automation.workspaceId) ?? null) : null;
 const availability = getAutomationTargetAvailability({ automation, repo, workspace, projectHostSetups, sshConnectionStates, runtimeStatusByEnvironmentId, automationHostTarget, sourceHostAvailability: automationSourceHostAvailabilityById.get(automation.id) });
 if (!availability.canRunNow) { toast.error(availability.message);
 return };
await runAutomationNowForTarget(automation, automationHostTarget);
 useAppStore.getState().recordFeatureInteraction('automation-run');
await hydratePersistedUIState();
await refresh();
 toast.message( translate('auto.components.automations.AutomationsPage.a1bdb57008', 'Automation run queued.') ) };
 const rerunAutomationRun = async (automation: Automation, run: AutomationRun): Promise<void> => {;
 const runId = run.id;
 if (rerunRunIdsInFlightRef.current.has(runId)) {;
 return };
 const pendingStartedAt = Date.now();
 rerunRunIdsInFlightRef.current.add(runId);
 setRerunRunIdsInFlight(new Set(rerunRunIdsInFlightRef.current));
 try { await runAutomationNowForTarget(automation, automationHostTarget);
await hydratePersistedUIState();
await refresh();
 toast.message( translate( 'auto.components.automations.AutomationsPage.a1bdb57008', 'Automation run queued.' ) ) } catch (error) { toast.error( error instanceof Error ? error.message : translate( 'auto.components.automations.AutomationsPage.3a4c476aa0', 'Failed to rerun automation.' ) );
await refresh() } finally { /* Why: fast skipped/failed reruns can settle before users or validation can see the guard.*/ await waitForAutomationRerunPendingVisibility(pendingStartedAt);
 rerunRunIdsInFlightRef.current.delete(runId);
 setRerunRunIdsInFlight(new Set(rerunRunIdsInFlightRef.current)) } };
 const openAutomationRunPage = (run: AutomationRun): void => { setSelectedAutomationRunPageId(run.id) };
 const openRunWorkspace = (run: AutomationRun): void => {;
 const runWorktree = run.workspaceId ? (worktreeMap.get(run.workspaceId) ?? null) : null;
 const store = useAppStore.getState();
 const openTabId = getAutomationRunOpenTabId(run);
 const terminalTabExists = openTabId ? Boolean(store.getTab(openTabId)) : false;
 const currentLayout = openTabId ? store.terminalLayoutsByTabId[openTabId] : null;
 const livePtyIds = openTabId ? (store.ptyIdsByTabId[openTabId] ?? []) : [];
 const terminalTarget = resolveAutomationRunOpenTarget({ run, terminalTabExists, currentLayout, livePtyIds });
 const runViewState = getAutomationRunViewState({ run, workspaceExists: Boolean(runWorktree), terminalTargetExists: terminalTarget !== null });
 if (!run.workspaceId || !runWorktree || !runViewState.canOpen) { toast.error(runViewState.statusLabel);
 return };
 if (runViewState.availability === 'terminal' && !terminalTarget) { toast.error(runViewState.statusLabel);
 return };
 if (terminalTarget && currentLayout) { store.setTabLayout( terminalTarget.tabId, buildAutomationRunOpenLayout({ target: terminalTarget, currentLayout }) );
 if (activateAndRevealWorktree(run.workspaceId)) { store.setActiveTab(terminalTarget.tabId);
 store.setActiveTabType('terminal');
 return } };
 if (!activateAndRevealWorktree(run.workspaceId)) { toast.error( translate( 'auto.components.automations.AutomationsPage.e1bf9b1512', 'Workspace is not available.' ) );
 return } /* Why: activation can create a fresh terminal for an empty workspace;
 tell*/ /* users when that is not the original automation run session.*/ toast.message(runViewState.statusLabel) };
 useEffect(() => {;
 if (createOpen || deleteTarget || externalDeleteTarget) {;
 return };
 function onKeyDown(event: KeyboardEvent): void {;
 if (event.key !== 'Escape' || event.defaultPrevented) {;
 return };
 const target = event.target;
 if (!(target instanceof HTMLElement)) {;
 return } /* Why: match Tasks page behavior: Esc first exits field focus, then exits*/ /* the page once focus is back on page chrome.*/ if ( target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target instanceof HTMLSelectElement || target.isContentEditable ) { event.preventDefault();
 target.blur();
 return };
 event.preventDefault();
 closeAutomationsPage() };
 window.addEventListener('keydown', onKeyDown, { capture: true });
 return () => window.removeEventListener('keydown', onKeyDown, { capture: true }) }, [closeAutomationsPage, createOpen, deleteTarget, externalDeleteTarget]);
 return <AutomationsPageRenderer {...{ activePaneTab, applyTemplateToDraft, automationHostTarget, automationSourceHostAvailabilityById, automationYamlHooksByRepoKey, automations, canRerunSelectedAutomationRunPage, canSaveDraft, closeAutomationsPage, confirmDeleteAutomation, confirmDeleteExternalAutomation, connectExternalAutomationSource, createOpen, createTarget, deleteConfirmButtonRef, deleteTarget, dontAskDeleteAgain, draft, editingAutomationId, editingExternalTarget, externalActionKey, externalAutomationEntries, externalDeleteTarget, fetchExternalAutomationRuns, getAutomationHooksCacheKey, getAutomationRepoHostLabel, handleCreateTargetChange, handleProjectChange, hostLabelById, isLoading, isSaving, isSelectedAutomationRunPageRerunPending, markSetupDecisionTouched, openAutomationRunPage, openCreateDialog, openEditDialog, openEditExternalDialog, openExternalRunPage, openRunWorkspace, projectHostSetups, refresh, relativeNow, repoMap, repos, requestDeleteAutomation, requestExternalAction, rerunAutomationRun, runNow, runs, runtimeStatusByEnvironmentId, saveAutomation, selectAutomationId, selectExternalKey, selected, selectedAutomationRunPage, selectedAutomationRunPageViewState, selectedAutomationRunPageWorkspaceDisplay, selectedExternal, selectedExternalRunPage, selectedExternalSourceAvailability, selectedExternalSshConnected, selectedExternalSshSource, selectedRepo, selectedRunNowAvailability, selectedRuns, selectedWorktree, setActivePaneTab, setCreateOpen, setDeleteTarget, setDontAskDeleteAgain, setDraft, setExternalDeleteTarget, setSelectedAutomationRunPageId, setSelectedExternalRunPage, settings, sshConnectionStates, toggleAutomation, worktreeMap, worktrees }} />
}
