export type ChecksPanelCommentFetchKey =
  | 'activeGitLabReview'
  | 'branch'
  | 'checksPanelAsyncResultKey'
  | 'fetchPRCheckDetails'
  | 'fetchPRComments'
  | 'isCurrentAsyncResult'
  | 'isPanelVisible'
  | 'pr'
  | 'prCacheKey'
  | 'prNumber'
  | 'repo'
  | 'setComments'
  | 'setCommentsLoading'
  | 'fetchComments'
  | 'handleLoadCheckDetails'
