export type ChecksPanelFetchKey =
  | 'activeGitLabReview'
  | 'asyncResultKeyRef'
  | 'branch'
  | 'fetchPRChecks'
  | 'hostedReviewCacheKey'
  | 'isCurrentAsyncResult'
  | 'pollIntervalRef'
  | 'pr'
  | 'prCacheKey'
  | 'prNumber'
  | 'prevChecksRef'
  | 'repo'
  | 'setChecks'
  | 'setChecksLoading'
  | 'setComments'
  | 'setCommentsLoading'
  | 'settings'
  | 'fetchChecks'
  | 'fetchGitLabDetails'
  | 'fetchComments'
  | 'handleLoadCheckDetails'
;
