export type ChecksPanelCreateKey =
  | 'activePullRequestGenerationKey'
  | 'activeWorktreeId'
  | 'activeWorktreePath'
  | 'branch'
  | 'createComposerOpen'
  | 'createHostedReview'
  | 'createPrInFlightRef'
  | 'createPrPushFirst'
  | 'hostedReviewCreateCopy'
  | 'hostedReviewCreateProvider'
  | 'hostedReviewCreation'
  | 'panelContextKey'
  | 'panelContextKeyRef'
  | 'prCreationDefaults'
  | 'repo'
  | 'setCreatePrError'
  | 'setGitStatusRefreshNonce'
  | 'setIsCreatingPr'
  | 'updatePullRequestGenerationRecord'
;
