export type ChecksPanelRefreshKey =
  | 'activeConnectionId'
  | 'activeGitLabReview'
  | 'activeWorktreeId'
  | 'activeWorktreePath'
  | 'activeWorktreePushTarget'
  | 'asyncResultKeyRef'
  | 'branch'
  | 'expireGitHubPRRefreshState'
  | 'fallbackGitHubPRNumber'
  | 'fetchChecks'
  | 'fetchGitLabDetails'
  | 'fetchHostedReviewForBranch'
  | 'fetchPRChecks'
  | 'fetchPRComments'
  | 'fetchPRForBranch'
  | 'hasUncommittedChanges'
  | 'isCurrentAsyncResult'
  | 'isFolder'
  | 'isGitLabReviewContext'
  | 'linkedAzureDevOpsPR'
  | 'linkedBitbucketPR'
  | 'linkedGitLabMR'
  | 'linkedGiteaPR'
  | 'linkedPR'
  | 'ownerSettings'
  | 'panelContextKey'
  | 'panelContextKeyRef'
  | 'pollIntervalRef'
  | 'pr'
  | 'prCacheKey'
  | 'prNumber'
  | 'prevChecksRef'
  | 'rawPRRefreshState'
  | 'refreshInFlightRef'
  | 'refreshRequestKeyRef'
  | 'remoteStatus'
  | 'repo'
  | 'setChecks'
  | 'setChecksLoading'
  | 'setComments'
  | 'setCommentsLoading'
  | 'setEligibilityRefreshNonce'
  | 'setGitStatusSnapshot'
  | 'setIsRefreshing'
  | 'settings'
  | 'updateWorktreeGitIdentity'
;
export type ChecksPanelRefreshContext<T extends Record<string, unknown>> = T & {
  [K in ChecksPanelRefreshKey]: K extends keyof T ? T[K] : never
}
