export type ChecksPanelGenerationKey =
  | 'activePullRequestGenerationKey'
  | 'activePullRequestGenerationRecord'
  | 'activePullRequestGenerationSeedRestoreKey'
  | 'activeReview'
  | 'activeWorktreeId'
  | 'activeWorktreePath'
  | 'allocatePullRequestGenerationRequestId'
  | 'branch'
  | 'confirmedReadiness'
  | 'fetchUpstreamStatus'
  | 'hostedReviewCreateProvider'
  | 'hostedReviewCreation'
  | 'isFolder'
  | 'ownerSettings'
  | 'pr'
  | 'prGenerationRecords'
  | 'repo'
  | 'setCreatePrError'
  | 'setPullRequestGenerationRecord'
  | 'settings'
  | 'updatePullRequestGenerationRecord'
;
